package objects

// The builtin exception class hierarchy, generated by walking builtins in
// CPython 3.14.6: every class deriving from BaseException, mapped to its
// __bases__ names. Most classes have a single base; ExceptionGroup is the
// one dual-inheritance case (BaseExceptionGroup and Exception), so values
// are slices.
var excBases = map[string][]string{
	"BaseException":             nil,
	"ArithmeticError":           {"Exception"},
	"AssertionError":            {"Exception"},
	"AttributeError":            {"Exception"},
	"BaseExceptionGroup":        {"BaseException"},
	"BlockingIOError":           {"OSError"},
	"BrokenPipeError":           {"ConnectionError"},
	"BufferError":               {"Exception"},
	"BytesWarning":              {"Warning"},
	"ChildProcessError":         {"OSError"},
	"ConnectionAbortedError":    {"ConnectionError"},
	"ConnectionError":           {"OSError"},
	"ConnectionRefusedError":    {"ConnectionError"},
	"ConnectionResetError":      {"ConnectionError"},
	"DeprecationWarning":        {"Warning"},
	"EOFError":                  {"Exception"},
	"EncodingWarning":           {"Warning"},
	"Exception":                 {"BaseException"},
	"ExceptionGroup":            {"BaseExceptionGroup", "Exception"},
	"FileExistsError":           {"OSError"},
	"FileNotFoundError":         {"OSError"},
	"FloatingPointError":        {"ArithmeticError"},
	"FutureWarning":             {"Warning"},
	"GeneratorExit":             {"BaseException"},
	"ImportError":               {"Exception"},
	"ImportWarning":             {"Warning"},
	"IndentationError":          {"SyntaxError"},
	"IndexError":                {"LookupError"},
	"InterruptedError":          {"OSError"},
	"IsADirectoryError":         {"OSError"},
	"KeyError":                  {"LookupError"},
	"KeyboardInterrupt":         {"BaseException"},
	"LookupError":               {"Exception"},
	"MemoryError":               {"Exception"},
	"ModuleNotFoundError":       {"ImportError"},
	"NameError":                 {"Exception"},
	"NotADirectoryError":        {"OSError"},
	"NotImplementedError":       {"RuntimeError"},
	"OSError":                   {"Exception"},
	"OverflowError":             {"ArithmeticError"},
	"PendingDeprecationWarning": {"Warning"},
	"PermissionError":           {"OSError"},
	"ProcessLookupError":        {"OSError"},
	"PythonFinalizationError":   {"RuntimeError"},
	"RecursionError":            {"RuntimeError"},
	"ReferenceError":            {"Exception"},
	"ResourceWarning":           {"Warning"},
	"RuntimeError":              {"Exception"},
	"RuntimeWarning":            {"Warning"},
	"StopAsyncIteration":        {"Exception"},
	"StopIteration":             {"Exception"},
	"SyntaxError":               {"Exception"},
	"SyntaxWarning":             {"Warning"},
	"SystemError":               {"Exception"},
	"SystemExit":                {"BaseException"},
	"TabError":                  {"IndentationError"},
	"TimeoutError":              {"OSError"},
	"TypeError":                 {"Exception"},
	"UnboundLocalError":         {"NameError"},
	"UnicodeDecodeError":        {"UnicodeError"},
	"UnicodeEncodeError":        {"UnicodeError"},
	"UnicodeError":              {"ValueError"},
	"UnicodeTranslateError":     {"UnicodeError"},
	"UnicodeWarning":            {"Warning"},
	"UserWarning":               {"Warning"},
	"ValueError":                {"Exception"},
	"Warning":                   {"Exception"},
	"ZeroDivisionError":         {"ArithmeticError"},
	"_IncompleteInputError":     {"SyntaxError"},
}

// excAlias maps the two legacy builtin names to the class they alias.
// dir(builtins) lists them, but their __name__ is OSError.
var excAlias = map[string]string{
	"EnvironmentError": "OSError",
	"IOError":          "OSError",
}

func excCanon(name string) string {
	if c, ok := excAlias[name]; ok {
		return c
	}
	return name
}

// IsExceptionClass reports whether name is a builtin exception class,
// counting the OSError aliases.
func IsExceptionClass(name string) bool {
	_, ok := excBases[excCanon(name)]
	return ok
}

// Matches reports whether an exception of the given kind is an instance
// of class, walking the base table. Both dual bases of ExceptionGroup
// count, like real MRO membership would.
func Matches(kind, class string) bool {
	kind, class = excCanon(kind), excCanon(class)
	if kind == class {
		_, ok := excBases[kind]
		return ok
	}
	for _, b := range excBases[kind] {
		if Matches(b, class) {
			return true
		}
	}
	return false
}
