// Code generated by tools/tokens_go from cpython/Grammar/Tokens and
// cpython/Include/internal/pycore_token.h. DO NOT EDIT.
//
// CPython: Include/internal/pycore_token.h
// CPython: Grammar/Tokens

package pytoken

// Token kinds, numeric values pinned to CPython's token.h. The
// ALL_CAPS spellings preserve parity with `token.tok_name` so
// fixture comparisons line up byte-for-byte.
//
//nolint:revive // ALL_CAPS names mirror CPython token.h.
const (
	ENDMARKER        Type = 0
	NAME             Type = 1
	NUMBER           Type = 2
	STRING           Type = 3
	NEWLINE          Type = 4
	INDENT           Type = 5
	DEDENT           Type = 6
	LPAR             Type = 7
	RPAR             Type = 8
	LSQB             Type = 9
	RSQB             Type = 10
	COLON            Type = 11
	COMMA            Type = 12
	SEMI             Type = 13
	PLUS             Type = 14
	MINUS            Type = 15
	STAR             Type = 16
	SLASH            Type = 17
	VBAR             Type = 18
	AMPER            Type = 19
	LESS             Type = 20
	GREATER          Type = 21
	EQUAL            Type = 22
	DOT              Type = 23
	PERCENT          Type = 24
	LBRACE           Type = 25
	RBRACE           Type = 26
	EQEQUAL          Type = 27
	NOTEQUAL         Type = 28
	LESSEQUAL        Type = 29
	GREATEREQUAL     Type = 30
	TILDE            Type = 31
	CIRCUMFLEX       Type = 32
	LEFTSHIFT        Type = 33
	RIGHTSHIFT       Type = 34
	DOUBLESTAR       Type = 35
	PLUSEQUAL        Type = 36
	MINEQUAL         Type = 37
	STAREQUAL        Type = 38
	SLASHEQUAL       Type = 39
	PERCENTEQUAL     Type = 40
	AMPEREQUAL       Type = 41
	VBAREQUAL        Type = 42
	CIRCUMFLEXEQUAL  Type = 43
	LEFTSHIFTEQUAL   Type = 44
	RIGHTSHIFTEQUAL  Type = 45
	DOUBLESTAREQUAL  Type = 46
	DOUBLESLASH      Type = 47
	DOUBLESLASHEQUAL Type = 48
	AT               Type = 49
	ATEQUAL          Type = 50
	RARROW           Type = 51
	ELLIPSIS         Type = 52
	COLONEQUAL       Type = 53
	EXCLAMATION      Type = 54
	OP               Type = 55
	TYPE_IGNORE      Type = 56
	TYPE_COMMENT     Type = 57
	SOFT_KEYWORD     Type = 58
	FSTRING_START    Type = 59
	FSTRING_MIDDLE   Type = 60
	FSTRING_END      Type = 61
	TSTRING_START    Type = 62
	TSTRING_MIDDLE   Type = 63
	TSTRING_END      Type = 64
	COMMENT          Type = 65
	NL               Type = 66
	ERRORTOKEN       Type = 67
	ENCODING         Type = 68
	NTokens          Type = 69
)

// tokenNames is indexed by Type. CPython parity with token.tok_name.
var tokenNames = [...]string{
	ENDMARKER:        "ENDMARKER",
	NAME:             "NAME",
	NUMBER:           "NUMBER",
	STRING:           "STRING",
	NEWLINE:          "NEWLINE",
	INDENT:           "INDENT",
	DEDENT:           "DEDENT",
	LPAR:             "LPAR",
	RPAR:             "RPAR",
	LSQB:             "LSQB",
	RSQB:             "RSQB",
	COLON:            "COLON",
	COMMA:            "COMMA",
	SEMI:             "SEMI",
	PLUS:             "PLUS",
	MINUS:            "MINUS",
	STAR:             "STAR",
	SLASH:            "SLASH",
	VBAR:             "VBAR",
	AMPER:            "AMPER",
	LESS:             "LESS",
	GREATER:          "GREATER",
	EQUAL:            "EQUAL",
	DOT:              "DOT",
	PERCENT:          "PERCENT",
	LBRACE:           "LBRACE",
	RBRACE:           "RBRACE",
	EQEQUAL:          "EQEQUAL",
	NOTEQUAL:         "NOTEQUAL",
	LESSEQUAL:        "LESSEQUAL",
	GREATEREQUAL:     "GREATEREQUAL",
	TILDE:            "TILDE",
	CIRCUMFLEX:       "CIRCUMFLEX",
	LEFTSHIFT:        "LEFTSHIFT",
	RIGHTSHIFT:       "RIGHTSHIFT",
	DOUBLESTAR:       "DOUBLESTAR",
	PLUSEQUAL:        "PLUSEQUAL",
	MINEQUAL:         "MINEQUAL",
	STAREQUAL:        "STAREQUAL",
	SLASHEQUAL:       "SLASHEQUAL",
	PERCENTEQUAL:     "PERCENTEQUAL",
	AMPEREQUAL:       "AMPEREQUAL",
	VBAREQUAL:        "VBAREQUAL",
	CIRCUMFLEXEQUAL:  "CIRCUMFLEXEQUAL",
	LEFTSHIFTEQUAL:   "LEFTSHIFTEQUAL",
	RIGHTSHIFTEQUAL:  "RIGHTSHIFTEQUAL",
	DOUBLESTAREQUAL:  "DOUBLESTAREQUAL",
	DOUBLESLASH:      "DOUBLESLASH",
	DOUBLESLASHEQUAL: "DOUBLESLASHEQUAL",
	AT:               "AT",
	ATEQUAL:          "ATEQUAL",
	RARROW:           "RARROW",
	ELLIPSIS:         "ELLIPSIS",
	COLONEQUAL:       "COLONEQUAL",
	EXCLAMATION:      "EXCLAMATION",
	OP:               "OP",
	TYPE_IGNORE:      "TYPE_IGNORE",
	TYPE_COMMENT:     "TYPE_COMMENT",
	SOFT_KEYWORD:     "SOFT_KEYWORD",
	FSTRING_START:    "FSTRING_START",
	FSTRING_MIDDLE:   "FSTRING_MIDDLE",
	FSTRING_END:      "FSTRING_END",
	TSTRING_START:    "TSTRING_START",
	TSTRING_MIDDLE:   "TSTRING_MIDDLE",
	TSTRING_END:      "TSTRING_END",
	COMMENT:          "COMMENT",
	NL:               "NL",
	ERRORTOKEN:       "ERRORTOKEN",
	ENCODING:         "ENCODING",
}
