// Package lower turns the frontend AST into a Go main package. The boxed
// tier is the only tier until M4: every value is an objects.Object, every
// fallible operation runs through pkg/objects, and expression trees flatten
// into checked temporaries. The output is deterministic and gofmt-clean;
// making it pretty is the typed tier's job in later milestones.
//
// Every generated statement, expression, and declaration is built as a go/ast
// node and composed by nesting nodes, so a malformed splice is a type error
// at construction rather than invalid Go discovered at format time. The only
// place nodes become text is the assembly seam in Module; the node
// constructors live in goast.go.
//
// The lowering itself is spread by concern: funcgen.go builds function
// bodies, stmt.go and expr.go handle the plain statement and expression
// forms, call.go resolves callees, and exceptions.go owns try, raise, and
// assert.
package lower

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"strconv"

	"github.com/tamnd/unagi/pkg/frontend"
)

// Error is a compile-time rejection with a source position, for constructs
// the lowering does not handle yet.
type Error struct {
	File string
	Pos  frontend.Pos
	Msg  string
}

func (e *Error) Error() string {
	return fmt.Sprintf("%s:%d:%d: error: %s", e.File, e.Pos.Line, e.Pos.Col, e.Msg)
}

// Module lowers a parsed module to a complete Go main package. file is the
// source path as given on the command line; it lands in the generated
// header, in compile errors, and in traceback frames. source is the raw
// Python text, embedded in the binary so tracebacks can print excerpt
// lines; nil skips the embedding and frames render bare, which is what
// CPython prints when the source file is gone.
func Module(mod *frontend.Module, file string, source []byte) ([]byte, error) {
	e := &emitter{file: file, defs: map[string]*frontend.FuncDef{}, defOrd: map[string]int{}}

	var body []frontend.Stmt
	var defs []*frontend.FuncDef
	for _, s := range mod.Body {
		if d, ok := s.(*frontend.FuncDef); ok {
			if _, dup := e.defs[d.Name]; dup {
				// Redefinition is legal Python; M0 hoists defs, so the second
				// binding cannot take effect and we refuse it instead.
				return nil, e.errf(d.Span(), "redefining function %q is not supported in M0", d.Name)
			}
			e.defOrd[d.Name] = len(defs)
			for _, p := range d.Params {
				if p.Default != nil {
					e.slots = append(e.slots, e.slotName(d.Name, p.Name))
					e.usedObjects = true
				}
			}
			e.defs[d.Name] = d
			defs = append(defs, d)
		}
		// Defs stay in the body: the def statement evaluates its parameter
		// defaults when it executes, so the slot fills at that point.
		body = append(body, s)
	}

	var fnDecls []*ast.FuncDecl
	for _, d := range defs {
		decl, err := e.emitFunc(d)
		if err != nil {
			return nil, err
		}
		fnDecls = append(fnDecls, decl)
	}
	pymain, err := e.emitMain(body)
	if err != nil {
		return nil, err
	}

	// The assembly seam: the one place nodes become text. The header comment,
	// package clause, and import block are plain lines, each declaration
	// prints through format.Node, and each def's doc comment goes down as a
	// text line right before its decl. Nothing above this point writes Go
	// syntax as strings.
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by unagi from %s. DO NOT EDIT.\n", file)
	out.WriteString("package main\n\nimport (\n\t\"os\"\n\n")
	if e.usedObjects {
		out.WriteString("\t\"github.com/tamnd/unagi/pkg/objects\"\n")
	}
	out.WriteString("\t\"github.com/tamnd/unagi/pkg/runtime\"\n)\n\n")
	if e.usedTB {
		fmt.Fprintf(&out, "// pyFile is the source path traceback frames cite.\nconst pyFile = %s\n\n", strconv.Quote(file))
		if len(source) > 0 {
			fmt.Fprintf(&out, "// pySource is the embedded source, so tracebacks can quote the line\n// under each frame the way CPython does.\nconst pySource = %s\n\nfunc init() { runtime.SetSource(pySource) }\n\n", strconv.Quote(string(source)))
		}
	}
	if len(e.slots) > 0 {
		out.WriteString("// Parameter default slots, assigned when each def statement runs.\nvar (\n")
		for _, s := range e.slots {
			fmt.Fprintf(&out, "\t%s objects.Object\n", s)
		}
		out.WriteString(")\n\n")
	}
	if err := writeDecl(&out, mainDecl()); err != nil {
		return nil, err
	}
	if err := writeDecl(&out, pymain); err != nil {
		return nil, err
	}
	for i, decl := range fnDecls {
		fmt.Fprintf(&out, "// %s is Python def %s.\n", mangle(defs[i].Name), defs[i].Name)
		if err := writeDecl(&out, decl); err != nil {
			return nil, err
		}
	}

	formatted, ferr := format.Source(out.Bytes())
	if ferr != nil {
		// A formatting failure is an emitter bug; surface the raw source so
		// it can be diagnosed from the error alone.
		return nil, fmt.Errorf("lower: generated invalid Go (%v):\n%s", ferr, out.String())
	}
	return formatted, nil
}

type emitter struct {
	file        string
	defs        map[string]*frontend.FuncDef
	defOrd      map[string]int
	slots       []string
	usedObjects bool
	usedTB      bool
}

// slotName is the module-level variable holding one parameter default,
// evaluated when the def statement runs. The def ordinal keeps names unique
// without leaning on the mangled namespace.
func (e *emitter) slotName(fname, pname string) string {
	return fmt.Sprintf("dflt%d_%s", e.defOrd[fname], pname)
}

func (e *emitter) errf(pos frontend.Pos, format string, args ...any) error {
	return &Error{File: e.file, Pos: pos, Msg: fmt.Sprintf(format, args...)}
}

// obj marks pkg/objects as imported and returns the qualified name node, so
// the import list stays exact even for programs that never touch a value.
func (e *emitter) obj(name string) ast.Expr {
	e.usedObjects = true
	return sel("objects", name)
}

func mangle(name string) string { return "u_" + name }
