//go:build !windows

package runtime

import "syscall"

// errnoNames is the POSIX name->number table, taken from Go's syscall constants
// so each host contributes its own values (EAGAIN is 35 on darwin, 11 on Linux),
// exactly as CPython's errno reads them from the build host's C headers. Any name
// absent on a host would fail the build, so it stays to the portable set.
// Canonical names come before their aliases (EAGAIN before EWOULDBLOCK) so the
// first mapping to a shared number is the one errorcode keeps.
var errnoNames = []errnoEntry{
	{"EPERM", int(syscall.EPERM)},
	{"ENOENT", int(syscall.ENOENT)},
	{"ESRCH", int(syscall.ESRCH)},
	{"EINTR", int(syscall.EINTR)},
	{"EIO", int(syscall.EIO)},
	{"ENXIO", int(syscall.ENXIO)},
	{"E2BIG", int(syscall.E2BIG)},
	{"ENOEXEC", int(syscall.ENOEXEC)},
	{"EBADF", int(syscall.EBADF)},
	{"ECHILD", int(syscall.ECHILD)},
	{"EAGAIN", int(syscall.EAGAIN)},
	{"ENOMEM", int(syscall.ENOMEM)},
	{"EACCES", int(syscall.EACCES)},
	{"EFAULT", int(syscall.EFAULT)},
	{"ENOTBLK", int(syscall.ENOTBLK)},
	{"EBUSY", int(syscall.EBUSY)},
	{"EEXIST", int(syscall.EEXIST)},
	{"EXDEV", int(syscall.EXDEV)},
	{"ENODEV", int(syscall.ENODEV)},
	{"ENOTDIR", int(syscall.ENOTDIR)},
	{"EISDIR", int(syscall.EISDIR)},
	{"EINVAL", int(syscall.EINVAL)},
	{"ENFILE", int(syscall.ENFILE)},
	{"EMFILE", int(syscall.EMFILE)},
	{"ENOTTY", int(syscall.ENOTTY)},
	{"ETXTBSY", int(syscall.ETXTBSY)},
	{"EFBIG", int(syscall.EFBIG)},
	{"ENOSPC", int(syscall.ENOSPC)},
	{"ESPIPE", int(syscall.ESPIPE)},
	{"EROFS", int(syscall.EROFS)},
	{"EMLINK", int(syscall.EMLINK)},
	{"EPIPE", int(syscall.EPIPE)},
	{"EDOM", int(syscall.EDOM)},
	{"ERANGE", int(syscall.ERANGE)},
	{"EDEADLK", int(syscall.EDEADLK)},
	{"ENAMETOOLONG", int(syscall.ENAMETOOLONG)},
	{"ENOLCK", int(syscall.ENOLCK)},
	{"ENOSYS", int(syscall.ENOSYS)},
	{"ENOTEMPTY", int(syscall.ENOTEMPTY)},
	{"ELOOP", int(syscall.ELOOP)},
	{"EWOULDBLOCK", int(syscall.EWOULDBLOCK)},
	{"ENOMSG", int(syscall.ENOMSG)},
	{"EIDRM", int(syscall.EIDRM)},
	{"EOVERFLOW", int(syscall.EOVERFLOW)},
	{"EILSEQ", int(syscall.EILSEQ)},
	{"ENOTSOCK", int(syscall.ENOTSOCK)},
	{"EDESTADDRREQ", int(syscall.EDESTADDRREQ)},
	{"EMSGSIZE", int(syscall.EMSGSIZE)},
	{"EPROTOTYPE", int(syscall.EPROTOTYPE)},
	{"ENOPROTOOPT", int(syscall.ENOPROTOOPT)},
	{"EPROTONOSUPPORT", int(syscall.EPROTONOSUPPORT)},
	{"EOPNOTSUPP", int(syscall.EOPNOTSUPP)},
	{"EAFNOSUPPORT", int(syscall.EAFNOSUPPORT)},
	{"EADDRINUSE", int(syscall.EADDRINUSE)},
	{"EADDRNOTAVAIL", int(syscall.EADDRNOTAVAIL)},
	{"ENETDOWN", int(syscall.ENETDOWN)},
	{"ENETUNREACH", int(syscall.ENETUNREACH)},
	{"ENETRESET", int(syscall.ENETRESET)},
	{"ECONNABORTED", int(syscall.ECONNABORTED)},
	{"ECONNRESET", int(syscall.ECONNRESET)},
	{"ENOBUFS", int(syscall.ENOBUFS)},
	{"EISCONN", int(syscall.EISCONN)},
	{"ENOTCONN", int(syscall.ENOTCONN)},
	{"ETIMEDOUT", int(syscall.ETIMEDOUT)},
	{"ECONNREFUSED", int(syscall.ECONNREFUSED)},
	{"EHOSTDOWN", int(syscall.EHOSTDOWN)},
	{"EHOSTUNREACH", int(syscall.EHOSTUNREACH)},
	{"EALREADY", int(syscall.EALREADY)},
	{"EINPROGRESS", int(syscall.EINPROGRESS)},
	{"ESTALE", int(syscall.ESTALE)},
	{"EDQUOT", int(syscall.EDQUOT)},
	{"ECANCELED", int(syscall.ECANCELED)},
	{"EOWNERDEAD", int(syscall.EOWNERDEAD)},
	{"ENOTRECOVERABLE", int(syscall.ENOTRECOVERABLE)},
}
