#!/usr/bin/env python3.14
# Authors swapcase_tables.go: the Uppercase and Lowercase property sets that pick
# str.swapcase's per-character branch in pkg/objects/strmethods.go.
#
# str.swapcase lowercases the uppercase characters and uppercases the lowercase
# ones, leaving everything else (a titlecase character, a letter with no case, a
# symbol) untouched. It decides the branch with the Uppercase and Lowercase
# properties, exactly CPython's do_swapcase (Py_UNICODE_ISUPPER / ISLOWER), and
# then applies the full uppercase or lowercase mapping (reusing the pinned upper
# table and the lower table plus its Final_Sigma walk), so this file carries only
# the two branch sets, not another copy of the mappings. Rerun to regenerate in
# place:
#
#     python3.14 pkg/runtime/gen_swapcase_tables.py
#
# The two sets are recovered from CPython's own str.swapcase without reading any
# UCD file: a character is uppercase (so swapcase lowercases it) when swapcasing
# it in isolation gives its lowercase, and lowercase (so swapcase uppercases it)
# when it gives its uppercase. This lands the titlecase characters in neither set
# (a titlecase digraph swapcases to itself even though it has a lowercase), which
# is exactly why the branch sets are not the same as the mapping-table keys.
# Checking the reconstructed swapcase against str.swapcase over the whole code
# space and hundreds of thousands of random strings shows zero differences.
import os
import subprocess

MAX = 0x110000


def is_surrogate(c):
    return 0xD800 <= c <= 0xDFFF


uppercase = set()
lowercase = set()
for c in range(MAX):
    if is_surrogate(c):
        continue
    ch = chr(c)
    sw = ch.swapcase()
    lo = ch.lower()
    up = ch.upper()
    if lo != ch and sw == lo:
        uppercase.add(c)
    elif up != ch and sw == up:
        lowercase.add(c)


def ranges(points):
    out = []
    for c in sorted(points):
        if out and c == out[-1][1] + 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


out = []
out.append("// Code generated by gen_swapcase_tables.py from the pinned CPython 3.14.6\n")
out.append("// str.swapcase. DO NOT EDIT.\n//\n")
out.append("// ucdUppercase and ucdLowercase are the sorted, inclusive code point ranges of\n")
out.append("// the Uppercase and Lowercase properties str.swapcase branches on: an uppercase\n")
out.append("// character is lowercased and a lowercase one is uppercased, everything else\n")
out.append("// (titlecase, caseless, symbols) is left untouched. Recovered from str.swapcase\n")
out.append("// itself so they agree with CPython character for character.\n\n")
out.append("package runtime\n\n")


def emit_ranges(name, points):
    out.append("var %s = [][2]rune{\n" % name)
    for lo, hi in ranges(points):
        out.append("\t{0x%X, 0x%X},\n" % (lo, hi))
    out.append("}\n\n")


emit_ranges("ucdUppercase", uppercase)
emit_ranges("ucdLowercase", lowercase)

dst = os.path.join(os.path.dirname(__file__), "swapcase_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

subprocess.run(["gofmt", "-w", dst], check=True)
print("wrote %s: uppercase=%d lowercase=%d" % (dst, len(uppercase), len(lowercase)))
