# Regenerate pkg/runtime/codecs_cn_tables.go from the host CPython oracle.
#
# gb2312 is a clean double-byte codec: bytes < 0x80 pass through as ascii, and a
# lead 0xA1..0xF7 with a trail 0xA1..0xFE selects one BMP code point. The mapping
# is a bijection over its double-byte set. We probe every candidate pair through
# the oracle decoder, keep the ones that decode to exactly one character, invert
# that to build the encoder, and round-trip every entry back through the oracle
# encoder so the Go tables are byte-exact against CPython 3.14.
#
# Run from the repo root with the same interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_cn_tables.py
# then `gofmt -w pkg/runtime/codecs_cn_tables.go`.

dec = {}
for lead in range(0x81, 0xff):
    for trail in range(0x40, 0xff):
        b = bytes([lead, trail])
        try:
            s = b.decode("gb2312")
        except UnicodeDecodeError:
            continue
        if len(s) != 1:
            raise SystemExit("multi-char decode for %02x%02x" % (lead, trail))
        dec[(lead, trail)] = ord(s)

enc = {}
for (lead, trail), cp in dec.items():
    if cp in enc:
        raise SystemExit("ambiguous encode for U+%04X" % cp)
    enc[cp] = (lead, trail)

for cp, (lead, trail) in enc.items():
    got = chr(cp).encode("gb2312")
    if got != bytes([lead, trail]):
        raise SystemExit("encode mismatch U+%04X" % cp)

items = sorted(dec.items())
out = []
out.append("// Code generated by gen_codecs_cn_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// gb2312 mapping tables, generated byte-exact from the CPython oracle (host")
out.append("// python3.14, the interpreter the conformance corpus records against). gb2312")
out.append("// is a double-byte codec: a lead byte 0xA1..0xF7 and a trail 0xA1..0xFE select")
out.append("// one BMP code point, and the mapping is a bijection over that set.")
out.append("")
out.append("package runtime")
out.append("")
out.append("// gb2312DecodeTable maps a double-byte key (lead<<8 | trail) to its code point,")
out.append("// %d entries." % len(items))
out.append("var gb2312DecodeTable = map[uint16]rune{")
for (lead, trail), cp in items:
    out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, cp))
out.append("}")
out.append("")
out.append("// gb2312EncodeTable maps a code point to its double-byte value (lead<<8 |")
out.append("// trail), the inverse of gb2312DecodeTable, %d entries." % len(items))
out.append("var gb2312EncodeTable = map[rune]uint16{")
for cp, (lead, trail) in sorted(enc.items()):
    out.append("\t0x%04X: 0x%04X," % (cp, (lead << 8) | trail))
out.append("}")
out.append("")
open("pkg/runtime/codecs_cn_tables.go", "w").write("\n".join(out))
print("entries:", len(items))
