# Regenerate pkg/runtime/codecs_iso2022_jp_tables.go from the host CPython oracle.
#
# iso2022_jp is a shift-state (escape-designation) codec: ESC sequences switch the
# G0 charset among ascii (ESC(B), JIS X 0201 roman (ESC(J) and JIS X 0208 (ESC$B,
# and ESC$@ for the 1978 revision, both decoded through the same table). ascii and
# roman are handled in code (roman differs from ascii only at 0x5c and 0x7e), so
# the one table this codec needs is JIS X 0208: the GL byte pair (0x21..0x7e each)
# to its code point and back. We probe every pair through the oracle decoder and
# build the encoder from the oracle encoder so both directions are byte-exact
# against CPython 3.14.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_iso2022_jp_tables.py
# then `gofmt -w pkg/runtime/codecs_iso2022_jp_tables.go`.

ESC_0208 = b"\x1b$B"


def build():
    decode = {}
    for lead in range(0x21, 0x7F):
        for trail in range(0x21, 0x7F):
            try:
                s = (ESC_0208 + bytes([lead, trail])).decode("iso2022_jp")
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("multi-char pair %02x%02x" % (lead, trail))
            decode[(lead, trail)] = ord(s)

    encode = {}
    for (lead, trail), cp in decode.items():
        b = chr(cp).encode("iso2022_jp")
        # A JIS X 0208 character encodes as ESC$B <lead> <trail> ESC(B; pull the
        # two GL bytes back out and keep the canonical pair for each code point.
        if not (b.startswith(ESC_0208) and b.endswith(b"\x1b(B")):
            continue
        pair = b[len(ESC_0208):-3]
        if len(pair) != 2:
            raise SystemExit("U+%04X encodes to %r" % (cp, b))
        encode.setdefault(cp, (pair[0], pair[1]))
    return decode, encode


decode, encode = build()

out = []
out.append("// Code generated by gen_codecs_iso2022_jp_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// JIS X 0208 mapping tables for iso2022_jp, generated byte-exact from the CPython")
out.append("// oracle (host python3.14, the interpreter the conformance corpus records")
out.append("// against). The key is the GL byte pair (lead<<8 | trail), each byte 0x21..0x7e.")
out.append("")
out.append("package runtime")
out.append("")
out.append("// iso2022JISX0208Decode maps a JIS X 0208 GL pair to its code point, %d entries." % len(decode))
out.append("var iso2022JISX0208Decode = map[uint16]rune{")
for (lead, trail) in sorted(decode):
    out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, decode[(lead, trail)]))
out.append("}")
out.append("")
out.append("// iso2022JISX0208Encode maps a code point to its JIS X 0208 GL pair, %d entries." % len(encode))
out.append("var iso2022JISX0208Encode = map[rune]uint16{")
for cp in sorted(encode):
    lead, trail = encode[cp]
    out.append("\t0x%04X: 0x%04X," % (cp, (lead << 8) | trail))
out.append("}")
out.append("")
open("pkg/runtime/codecs_iso2022_jp_tables.go", "w").write("\n".join(out))
print("iso2022_jp tables written: %d decode, %d encode" % (len(decode), len(encode)))
