# Regenerate pkg/runtime/codecs_jp_euc_tables.go from the host CPython oracle.
#
# euc_jp is a variable-width EUC codec the engine's mbEUCJPCodec drives: ascii
# decodes on its own, 0x8e (SS2) followed by one byte is a half-width katakana,
# 0x8f (SS3) followed by two bytes is a JIS X 0212 character, and any other high
# byte is the lead of a two-byte JIS X 0208 character. Every high byte begins a
# multibyte sequence, so the lead set is read off CPython's classification of a
# lone byte the same way the two-byte generators do.
#
# We probe every candidate sequence through the oracle decoder and build the
# encoder from the oracle encoder so both directions are byte-exact against
# CPython 3.14.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_jp_euc_tables.py
# then `gofmt -w pkg/runtime/codecs_jp_euc_tables.go`.

CODEC = "euc_jp"
PREFIX = "eucJP"
SS2 = 0x8E
SS3 = 0x8F


def build():
    leads = []
    for b in range(0x80, 0x100):
        try:
            bytes([b]).decode(CODEC)
        except UnicodeDecodeError as e:
            if "incomplete" in str(e):
                leads.append(b)

    double = {}
    for lead in leads:
        if lead == SS3:
            continue
        for trail in range(256):
            try:
                s = bytes([lead, trail]).decode(CODEC)
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("multi-char pair %02x%02x" % (lead, trail))
            double[(lead, trail)] = ord(s)

    triple = {}
    for b2 in range(256):
        for b3 in range(256):
            try:
                s = bytes([SS3, b2, b3]).decode(CODEC)
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("multi-char triple 8f%02x%02x" % (b2, b3))
            triple[(b2, b3)] = ord(s)

    enc_double = {}
    enc_triple = {}
    for cp in sorted(set(double.values()) | set(triple.values())):
        if cp < 0x80:
            continue
        b = chr(cp).encode(CODEC)
        if len(b) == 2:
            enc_double[cp] = (b[0] << 8) | b[1]
        elif len(b) == 3:
            if b[0] != SS3:
                raise SystemExit("U+%04X three-byte but not SS3" % cp)
            enc_triple[cp] = (b[1] << 8) | b[2]
        else:
            raise SystemExit("U+%04X encodes to %d bytes" % (cp, len(b)))
    return sorted(leads), double, triple, enc_double, enc_triple


leads, double, triple, enc_double, enc_triple = build()

out = []
out.append("// Code generated by gen_codecs_jp_euc_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// euc_jp mapping tables, generated byte-exact from the CPython oracle (host")
out.append("// python3.14, the interpreter the conformance corpus records against). euc_jp is")
out.append("// a variable-width EUC codec: ascii single bytes, 0x8e plus one byte for")
out.append("// half-width katakana, 0x8f plus two bytes for JIS X 0212, and any other high")
out.append("// byte as a two-byte JIS X 0208 lead.")
out.append("")
out.append("package runtime")
out.append("")
out.append("// %sLeads lists every byte that begins a multibyte sequence (0x8e and 0x8f" % PREFIX)
out.append("// included); a lone lead is incomplete and a bad trail is illegal.")
out.append("var %sLeads = []byte{%s}" % (PREFIX, ", ".join("0x%02X" % l for l in leads)))
out.append("")
out.append("// %sDoubleDecode maps a two-byte key (lead<<8 | trail) to its code point for" % PREFIX)
out.append("// the 0x8e half-width katakana and the JIS X 0208 plane, %d entries." % len(double))
out.append("var %sDoubleDecode = map[uint16]rune{" % PREFIX)
for (lead, trail) in sorted(double):
    out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, double[(lead, trail)]))
out.append("}")
out.append("")
out.append("// %sTripleDecode maps the two bytes after 0x8f (b2<<8 | b3) to their JIS X" % PREFIX)
out.append("// 0212 code point, %d entries." % len(triple))
out.append("var %sTripleDecode = map[uint16]rune{" % PREFIX)
for (b2, b3) in sorted(triple):
    out.append("\t0x%04X: 0x%04X," % ((b2 << 8) | b3, triple[(b2, b3)]))
out.append("}")
out.append("")
out.append("// %sDoubleEncode maps a code point to its two-byte value, %d entries." % (PREFIX, len(enc_double)))
out.append("var %sDoubleEncode = map[rune]uint16{" % PREFIX)
for cp in sorted(enc_double):
    out.append("\t0x%04X: 0x%04X," % (cp, enc_double[cp]))
out.append("}")
out.append("")
out.append("// %sTripleEncode maps a code point to the two bytes that follow 0x8f, %d" % (PREFIX, len(enc_triple)))
out.append("// entries.")
out.append("var %sTripleEncode = map[rune]uint16{" % PREFIX)
for cp in sorted(enc_triple):
    out.append("\t0x%04X: 0x%04X," % (cp, enc_triple[cp]))
out.append("}")
out.append("")
open("pkg/runtime/codecs_jp_euc_tables.go", "w").write("\n".join(out))
print("euc_jp tables written: %d leads, %d double, %d triple" % (len(leads), len(double), len(triple)))
