# Regenerate pkg/runtime/codecs_iso2022_jp2004_tables.go from the host CPython
# oracle.
#
# iso2022_jp_2004 carries the same charsets as iso2022_jp_3 (ascii, JIS X 0208 and
# the two JIS X 0213 planes) but designates JIS X 0213 plane 1 with the 2004
# revision escape ESC$(Q instead of ESC$(O. Plane 2 (ESC$(P) is the same plane as in
# iso2022_jp_3 and its decode table is identical, so this file reuses that decode map
# and only carries the plane 1 (ESC$(Q) tables and the plane 2 encode map, which
# differs from the iso2022_jp_3 one by a single code point.
#
# Plane 1 carries the same 25 combining sequences (a GL pair to a base plus U+309A).
# Some pairs are decode-only, and a character also in JIS X 0208 encodes through
# ESC$B, so a plane's encode map holds only the code points CPython routes through
# it. The generator asserts the plane encode maps do not overlap the shared JIS X
# 0208 map.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_iso2022_jp2004_tables.py
# then `gofmt -w pkg/runtime/codecs_iso2022_jp2004_tables.go`.

CODEC = "iso2022_jp_2004"
ESC_P1 = b"\x1b$(Q"
ESC_P2 = b"\x1b$(P"
ESC_ASCII = b"\x1b(B"


def scan_plane(esc):
    decode = {}
    decode2 = {}
    for lead in range(0x21, 0x7F):
        for trail in range(0x21, 0x7F):
            try:
                s = (esc + bytes([lead, trail]) + ESC_ASCII).decode(CODEC)
            except UnicodeDecodeError:
                continue
            if len(s) == 1:
                decode[(lead, trail)] = ord(s)
            elif len(s) == 2:
                decode2[(lead, trail)] = (ord(s[0]), ord(s[1]))
            else:
                raise SystemExit("pair %02x%02x -> %r" % (lead, trail, s))
    return decode, decode2


def build_encode(esc, decode, decode2):
    encode = {}
    encode2 = {}
    for (lead, trail), cp in decode.items():
        try:
            b = chr(cp).encode(CODEC)
        except UnicodeEncodeError:
            continue
        if b.startswith(esc) and b.endswith(ESC_ASCII) and b[len(esc):-3] == bytes([lead, trail]):
            encode.setdefault(cp, (lead, trail))
    for (lead, trail), (a, c) in decode2.items():
        try:
            b = (chr(a) + chr(c)).encode(CODEC)
        except UnicodeEncodeError:
            continue
        if b.startswith(esc) and b.endswith(ESC_ASCII) and b[len(esc):-3] == bytes([lead, trail]):
            encode2.setdefault((a, c), (lead, trail))
    return encode, encode2


jisx0208 = set()
for lead in range(0x21, 0x7F):
    for trail in range(0x21, 0x7F):
        try:
            s = (b"\x1b$B" + bytes([lead, trail]) + ESC_ASCII).decode("iso2022_jp")
        except UnicodeDecodeError:
            continue
        if len(s) == 1:
            b = chr(ord(s)).encode("iso2022_jp")
            if b.startswith(b"\x1b$B"):
                jisx0208.add(ord(s))

p1_dec, p1_dec2 = scan_plane(ESC_P1)
p2_dec, p2_dec2 = scan_plane(ESC_P2)
if p2_dec2:
    raise SystemExit("plane 2 unexpectedly has combining pairs")
p1_enc, p1_enc2 = build_encode(ESC_P1, p1_dec, p1_dec2)
p2_enc, _ = build_encode(ESC_P2, p2_dec, {})

overlap = (set(p1_enc) | set(p2_enc)) & jisx0208
if overlap:
    raise SystemExit("plane encode overlaps JIS X 0208: %r" % sorted(overlap)[:8])
base = sorted({a for (a, _c) in p1_enc2})

out = []
out.append("// Code generated by gen_codecs_iso2022_jp2004_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// JIS X 0213 plane 1 (ESC$(Q, the 2004 revision) tables for iso2022_jp_2004 plus its")
out.append("// plane 2 (ESC$(P) encode map, generated byte-exact from the CPython oracle (host")
out.append("// python3.14). The plane 2 decode map is identical to iso2022_jp_3's and is reused")
out.append("// from that file. The key is the GL byte pair (lead<<8 | trail), each byte")
out.append("// 0x21..0x7e. Plane 1 also carries 25 combining pairs that decode to a base plus")
out.append("// U+309A.")
out.append("")
out.append("package runtime")
out.append("")
out.append("// iso2022JISX0213P1QDecode maps a JIS X 0213 plane 1 (2004) GL pair to its code")
out.append("// point, %d entries." % len(p1_dec))
out.append("var iso2022JISX0213P1QDecode = map[uint16]rune{")
for (lead, trail) in sorted(p1_dec):
    out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, p1_dec[(lead, trail)]))
out.append("}")
out.append("")
out.append("// iso2022JISX0213P1QDecode2 maps a JIS X 0213 plane 1 (2004) GL pair to its two code")
out.append("// points (a base plus the combining mark U+309A), %d entries." % len(p1_dec2))
out.append("var iso2022JISX0213P1QDecode2 = map[uint16][2]rune{")
for (lead, trail) in sorted(p1_dec2):
    a, c = p1_dec2[(lead, trail)]
    out.append("\t0x%04X: {0x%04X, 0x%04X}," % ((lead << 8) | trail, a, c))
out.append("}")
out.append("")
out.append("// iso2022JISX0213P1QEncode maps a code point to its JIS X 0213 plane 1 (2004) GL")
out.append("// pair, %d entries." % len(p1_enc))
out.append("var iso2022JISX0213P1QEncode = map[rune]uint16{")
for cp in sorted(p1_enc):
    lead, trail = p1_enc[cp]
    out.append("\t0x%04X: 0x%04X," % (cp, (lead << 8) | trail))
out.append("}")
out.append("")
out.append("// iso2022JISX0213P1QEncode2 maps a base plus combining mark to its JIS X 0213 plane 1")
out.append("// (2004) GL pair, %d entries." % len(p1_enc2))
out.append("var iso2022JISX0213P1QEncode2 = map[[2]rune]uint16{")
for (a, c) in sorted(p1_enc2):
    lead, trail = p1_enc2[(a, c)]
    out.append("\t{0x%04X, 0x%04X}: 0x%04X," % (a, c, (lead << 8) | trail))
out.append("}")
out.append("")
out.append("// iso2022JISX0213P1QBase is the set of code points that can begin a plane 1 (2004)")
out.append("// combining pair, %d entries." % len(base))
out.append("var iso2022JISX0213P1QBase = map[rune]bool{")
for a in base:
    out.append("\t0x%04X: true," % a)
out.append("}")
out.append("")
out.append("// iso2022JISX0213P2QEncode maps a code point to its JIS X 0213 plane 2 GL pair as")
out.append("// iso2022_jp_2004 routes it, %d entries. It differs from the iso2022_jp_3 plane 2" % len(p2_enc))
out.append("// encode map by a single code point, so it is carried separately.")
out.append("var iso2022JISX0213P2QEncode = map[rune]uint16{")
for cp in sorted(p2_enc):
    lead, trail = p2_enc[cp]
    out.append("\t0x%04X: 0x%04X," % (cp, (lead << 8) | trail))
out.append("}")
out.append("")

open("pkg/runtime/codecs_iso2022_jp2004_tables.go", "w").write("\n".join(out))
print("iso2022_jp_2004 tables: p1 %d/%d (+%d comb), p2 enc %d, base %d" % (
    len(p1_dec), len(p1_enc), len(p1_dec2), len(p2_enc), len(base)))
