# Regenerate pkg/runtime/codecs_iso2022_jp2_tables.go from the host CPython oracle.
#
# iso2022_jp_2 adds three charsets to the iso2022_jp base: GB 2312 (designated ESC$A
# or ESC$(A), KSC 5601 (ESC$(C) and, on decode only, two single-byte G2 sets invoked
# with SS2 (ESC N): iso8859-1 (designated ESC.A) and iso8859-7 (ESC.F). The two-byte
# JIS X 0208 and JIS X 0212 charsets it shares with iso2022_jp and iso2022_jp_1 are
# reused from those table files, so this file carries only the GB 2312 and KSC 5601
# GL tables and the iso8859-7 G2 table (iso8859-1 is the identity b|0x80 and is built
# in code).
#
# The encoder tries the G0 charsets in the order ascii, JIS X 0208, JIS X 0212, GB
# 2312, KSC 5601, so a code point in more than one of them is emitted through the
# earliest, and never through SS2. The GB 2312 and KSC 5601 encode maps therefore
# hold only the code points CPython actually routes through them (disjoint from the
# JIS X 0208 and JIS X 0212 maps), which is what lets the runtime reuse those maps
# ahead of these without masking a character. The generator asserts that disjointness.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_iso2022_jp2_tables.py
# then `gofmt -w pkg/runtime/codecs_iso2022_jp2_tables.go`.

CODEC = "iso2022_jp_2"
ESC_ASCII = b"\x1b(B"


def scan_two(esc):
    # Decode every GL pair under a two-byte G0 designation.
    decode = {}
    for lead in range(0x21, 0x7F):
        for trail in range(0x21, 0x7F):
            try:
                s = (esc + bytes([lead, trail]) + ESC_ASCII).decode(CODEC)
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("pair %02x%02x -> %r" % (lead, trail, s))
            decode[(lead, trail)] = ord(s)
    return decode


def routed_encode(esc):
    # A code point belongs to this charset's encode map only when CPython's encoder
    # actually emits it through this escape.
    encode = {}
    for cp in range(0x80, 0x110000):
        try:
            b = chr(cp).encode(CODEC)
        except (UnicodeEncodeError, ValueError):
            continue
        if b.startswith(esc) and b.endswith(ESC_ASCII) and len(b) == len(esc) + 2 + 3:
            lead, trail = b[len(esc)], b[len(esc) + 1]
            encode[cp] = (lead, trail)
    return encode


def jisrep(esc):
    # The JIS X 0208 / 0212 code point sets, to assert the added charsets stay disjoint.
    rep = set()
    for cp in range(0x80, 0x110000):
        try:
            b = chr(cp).encode(CODEC)
        except (UnicodeEncodeError, ValueError):
            continue
        if b.startswith(esc):
            rep.add(cp)
    return rep


gb_esc = b"\x1b$(A"
ksc_esc = b"\x1b$(C"
gb_dec = scan_two(gb_esc)
ksc_dec = scan_two(ksc_esc)
gb_enc = routed_encode(gb_esc)
ksc_enc = routed_encode(ksc_esc)

jis = jisrep(b"\x1b$B") | jisrep(b"\x1b$(D")
overlap = (set(gb_enc) | set(ksc_enc)) & jis
if overlap:
    raise SystemExit("gb/ksc encode overlaps JIS: %r" % sorted(overlap)[:8])
if set(gb_enc) & set(ksc_enc):
    raise SystemExit("gb and ksc encode overlap")

# iso8859-7 G2 decode: the GL byte 0x20..0x7f invoked by SS2 maps to the code point
# iso8859-7 gives byte b|0x80. Some positions are undefined and are skipped.
greek = {}
for b in range(0x20, 0x80):
    try:
        greek[b] = ord(bytes([b | 0x80]).decode("iso8859-7"))
    except UnicodeDecodeError:
        continue

out = []
out.append("// Code generated by gen_codecs_iso2022_jp2_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// GB 2312 and KSC 5601 GL tables and the iso8859-7 G2 table for iso2022_jp_2,")
out.append("// generated byte-exact from the CPython oracle (host python3.14). The two-byte keys")
out.append("// are the GL pair (lead<<8 | trail), each byte 0x21..0x7e; the encode maps hold only")
out.append("// the code points CPython routes through GB 2312 / KSC 5601 rather than JIS X 0208 /")
out.append("// 0212. The G2 map is keyed by the single GL byte invoked with SS2.")
out.append("")
out.append("package runtime")
out.append("")


def emit_decode(name, dec, desc):
    out.append("// %s maps a %s GL pair to its code point, %d entries." % (name, desc, len(dec)))
    out.append("var %s = map[uint16]rune{" % name)
    for (lead, trail) in sorted(dec):
        out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, dec[(lead, trail)]))
    out.append("}")
    out.append("")


def emit_encode(name, enc, desc):
    out.append("// %s maps a code point to its %s GL pair, %d entries." % (name, desc, len(enc)))
    out.append("var %s = map[rune]uint16{" % name)
    for cp in sorted(enc):
        lead, trail = enc[cp]
        out.append("\t0x%04X: 0x%04X," % (cp, (lead << 8) | trail))
    out.append("}")
    out.append("")


emit_decode("iso2022GB2312Decode", gb_dec, "GB 2312")
emit_encode("iso2022GB2312Encode", gb_enc, "GB 2312")
emit_decode("iso2022KSC5601Decode", ksc_dec, "KSC 5601")
emit_encode("iso2022KSC5601Encode", ksc_enc, "KSC 5601")

out.append("// iso2022Latin7G2Decode maps a GL byte invoked with SS2 (after ESC.F) to its")
out.append("// iso8859-7 code point, %d entries." % len(greek))
out.append("var iso2022Latin7G2Decode = map[uint16]rune{")
for b in sorted(greek):
    out.append("\t0x%02X: 0x%04X," % (b, greek[b]))
out.append("}")
out.append("")

open("pkg/runtime/codecs_iso2022_jp2_tables.go", "w").write("\n".join(out))
print("iso2022_jp_2 tables: gb %d/%d ksc %d/%d greek %d" % (
    len(gb_dec), len(gb_enc), len(ksc_dec), len(ksc_enc), len(greek)))
