# Regenerate pkg/runtime/codecs_iso2022_kr_tables.go from the host CPython oracle.
#
# iso2022_kr is the Korean member of the ISO-2022 family and does not use the G0
# escape-designation model the JP codecs do. It designates KSC 5601 into G1 once with
# ESC$)C and then shifts between ascii (G0) and KSC 5601 (G1) with the SO (0x0e) and
# SI (0x0f) control bytes; a newline resets the shift back to ascii. Every non-ascii
# character therefore routes through KSC 5601, so unlike iso2022_jp_2 the encode map
# is the full KSC 5601 repertoire rather than a routed subset.
#
# The decode direction reuses the KSC 5601 decode table already generated for
# iso2022_jp_2 (the GL pairs are identical), so this file carries only the full
# encode map.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_iso2022_kr_tables.py
# then `gofmt -w pkg/runtime/codecs_iso2022_kr_tables.go`.

CODEC = "iso2022_kr"


def strip(b):
    # Remove the one-time G1 designation and the SO/SI shifts, leaving the GL pair.
    return b.replace(b"\x1b$)C", b"").replace(b"\x0e", b"").replace(b"\x0f", b"")


encode = {}
for cp in range(0x80, 0x110000):
    try:
        b = chr(cp).encode(CODEC)
    except (UnicodeEncodeError, ValueError):
        continue
    body = strip(b)
    if len(body) == 2 and 0x21 <= body[0] <= 0x7E and 0x21 <= body[1] <= 0x7E:
        encode[cp] = (body[0], body[1])

# Cross-check against the reused decode table so the two directions agree.
out = []
out.append("// Code generated by gen_codecs_iso2022_kr_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// The full KSC 5601 encode map for iso2022_kr, generated byte-exact from the CPython")
out.append("// oracle (host python3.14). The key is a code point and the value is the GL pair")
out.append("// (lead<<8 | trail), each byte 0x21..0x7e. The decode direction reuses the KSC 5601")
out.append("// decode table from codecs_iso2022_jp2_tables.go, whose GL pairs are identical.")
out.append("")
out.append("package runtime")
out.append("")
out.append("// iso2022KRKSCEncode maps a code point to its KSC 5601 GL pair, %d entries." % len(encode))
out.append("var iso2022KRKSCEncode = map[rune]uint16{")
for cp in sorted(encode):
    lead, trail = encode[cp]
    out.append("\t0x%04X: 0x%04X," % (cp, (lead << 8) | trail))
out.append("}")
out.append("")

open("pkg/runtime/codecs_iso2022_kr_tables.go", "w").write("\n".join(out))
print("iso2022_kr tables: ksc encode %d" % len(encode))
