#!/usr/bin/env python3.14
# Authors casefold_tables.go: the full Unicode case-folding map behind
# str.casefold in pkg/objects/strmethods.go.
#
# The map is captured straight from the pinned python3.14's own str.casefold (the
# conformance oracle), never hand-written, so it folds character for character the
# way CPython does. Go's stdlib carries an older UCD and has no full-fold table at
# all (unicode.SimpleFold is the 1:1 orbit walk, not the C+F folding str.casefold
# applies), which is why this cannot be composed from Go's unicode package and is
# pinned from the interpreter. Rerun to regenerate the file in place:
#
#     python3.14 pkg/runtime/gen_casefold_tables.py
#
# A code point is stored only when its fold actually changes it, so a lookup miss
# folds to the character itself (which is why a lone surrogate, with no fold, is
# left untouched).
import os
import subprocess

MAX = 0x110000

fold = {}
for c in range(MAX):
    ch = chr(c)
    f = ch.casefold()
    if f != ch:
        fold[c] = [ord(x) for x in f]

out = []
out.append("// Code generated by gen_casefold_tables.py from the pinned CPython 3.14.6\n")
out.append("// str.casefold. DO NOT EDIT.\n//\n")
out.append("// ucdCaseFold is the full case-folding map (Unicode CaseFolding.txt C+F status)\n")
out.append("// str.casefold applies: a code point maps to the sequence it folds to, and a\n")
out.append("// point absent here folds to itself. Captured from the interpreter so it agrees\n")
out.append("// with CPython character for character.\n\n")
out.append("package runtime\n\n")
out.append("var ucdCaseFold = map[rune][]rune{\n")
for c in sorted(fold):
    lit = "{" + ", ".join("0x%X" % r for r in fold[c]) + "}"
    out.append("\t0x%X: %s,\n" % (c, lit))
out.append("}\n")

dst = os.path.join(os.path.dirname(__file__), "casefold_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

# gofmt aligns the map-literal values so the emitted file matches what a reviewer's
# editor would produce and the repo stays gofmt-clean.
subprocess.run(["gofmt", "-w", dst], check=True)

print("wrote %s: fold=%d" % (dst, len(fold)))
