# Regenerate pkg/runtime/codecs_cn_gb18030_tables.go from the host CPython oracle.
#
# gb18030 is the full-Unicode member of the Chinese codec family. It has three
# byte forms: ascii single bytes, gbk-style two-byte pairs (a lead 0x81..0xFE and
# a non-digit trail), and a four-byte form (lead 0x81..0xFE, a digit 0x30..0x39,
# a lead 0x81..0xFE, a digit 0x30..0x39) that covers every remaining code point.
# The four-byte form is algorithmic: a linear index built from the four bytes
# maps to a code point by a small set of monotonic ranges (the BMP code points
# not in the one/two-byte set) plus one linear range for the whole supplementary
# plane. So we embed the two-byte tables in full and the four-byte form as its
# range table, both generated byte-exact from the oracle.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_cn_gb18030_tables.py
# then `gofmt -w pkg/runtime/codecs_cn_gb18030_tables.go`.

CODEC = "gb18030"


def lin_of(b1, b2, b3, b4):
    return (((b1 - 0x81) * 10 + (b2 - 0x30)) * 126 + (b3 - 0x81)) * 10 + (b4 - 0x30)


def build():
    # Two-byte decode: probe every lead/trail pair whose trail is not a digit
    # (a digit trail begins the four-byte form).
    double = {}
    for lead in range(0x81, 0xFF):
        for trail in range(256):
            if 0x30 <= trail <= 0x39:
                continue
            try:
                s = bytes([lead, trail]).decode(CODEC)
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("%s: multi-char pair %02x%02x" % (CODEC, lead, trail))
            double[(lead, trail)] = ord(s)

    enc_double = {}
    four_pts = []
    for cp in range(0x80, 0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        b = chr(cp).encode(CODEC)
        if len(b) == 2:
            enc_double[cp] = (b[0] << 8) | b[1]
        elif len(b) == 4:
            four_pts.append((cp, lin_of(*b)))
        else:
            raise SystemExit("%s: U+%04X encodes to %d bytes" % (CODEC, cp, len(b)))

    # Collapse the four-byte code points into monotonic ranges: a run of
    # consecutive code points whose (cp - lin) offset is constant is one range.
    four_pts.sort()
    ranges = []
    for cp, lin in four_pts:
        if ranges and cp == ranges[-1][2] + 1 and (cp - lin) == (ranges[-1][1] - ranges[-1][0]):
            ranges[-1][2] = cp
        else:
            ranges.append([lin, cp, cp])
    return double, enc_double, ranges


out = []
out.append("// Code generated by gen_codecs_cn_gb18030_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// gb18030 mapping tables, generated byte-exact from the CPython oracle (host")
out.append("// python3.14, the interpreter the conformance corpus records against). gb18030 is")
out.append("// a full-Unicode codec: ascii single bytes, gbk-style two-byte pairs (embedded in")
out.append("// full below), and an algorithmic four-byte form whose linear index maps to a")
out.append("// code point through the range table (the BMP code points outside the two-byte")
out.append("// set plus one linear range for the whole supplementary plane).")
out.append("")
out.append("package runtime")

double, enc_double, ranges = build()

out.append("")
out.append("// gb18030DoubleDecode maps a two-byte key (lead<<8 | trail) to its code")
out.append("// point, %d entries." % len(double))
out.append("var gb18030DoubleDecode = map[uint16]rune{")
for (lead, trail) in sorted(double):
    out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, double[(lead, trail)]))
out.append("}")
out.append("")
out.append("// gb18030DoubleEncode maps a code point to its two-byte value, %d entries." % len(enc_double))
out.append("var gb18030DoubleEncode = map[rune]uint16{")
for cp in sorted(enc_double):
    out.append("\t0x%04X: 0x%04X," % (cp, enc_double[cp]))
out.append("}")
out.append("")
out.append("// gb18030Range is one monotonic four-byte range: the code points cpStart..cpEnd")
out.append("// map to the linear indices linStart..linStart+(cpEnd-cpStart). The ranges are")
out.append("// sorted and non-overlapping in both the code-point and the linear-index axis,")
out.append("// so decode binary-searches by linear index and encode by code point.")
out.append("type gb18030Range struct{ linStart, cpStart, cpEnd uint32 }")
out.append("")
out.append("// gb18030Ranges is the four-byte range table, %d ranges." % len(ranges))
out.append("var gb18030Ranges = []gb18030Range{")
for lin, cs, ce in ranges:
    out.append("\t{0x%X, 0x%04X, 0x%04X}," % (lin, cs, ce))
out.append("}")

out.append("")
open("pkg/runtime/codecs_cn_gb18030_tables.go", "w").write("\n".join(out))
print("gb18030 tables written: %d double, %d ranges" % (len(double), len(ranges)))
