#!/usr/bin/env python3.14
# Authors uppercase_tables.go: the full Unicode uppercase map behind str.upper in
# pkg/objects/strmethods.go.
#
# The map is captured straight from the pinned python3.14's own str.upper (the
# conformance oracle), never hand-written, so it uppercases character for
# character the way CPython does. str.upper applies the full (multi-character)
# SpecialCasing mappings CPython bundles, so the German sharp s expands to SS and
# the ligatures to their letters, none of which Go's unicode.ToUpper (a 1:1
# mapping on an older UCD) reproduces, which is why the table is pinned from the
# interpreter. Uppercasing applies no context rule (the Final_Sigma and locale
# conditions are lowercasing or locale-specific), so a per-code-point table is
# byte-identical to str.upper on any string. Rerun to regenerate in place:
#
#     python3.14 pkg/runtime/gen_uppercase_tables.py
#
# A code point is stored only when its uppercase actually changes it, so a lookup
# miss uppercases to the character itself (which is why a lone surrogate, with no
# mapping, is left untouched).
import os
import subprocess

MAX = 0x110000

upper = {}
for c in range(MAX):
    ch = chr(c)
    u = ch.upper()
    if u != ch:
        upper[c] = [ord(x) for x in u]

out = []
out.append("// Code generated by gen_uppercase_tables.py from the pinned CPython 3.14.6\n")
out.append("// str.upper. DO NOT EDIT.\n//\n")
out.append("// ucdUpperFull is the full uppercase map (including the multi-character\n")
out.append("// SpecialCasing expansions, like the German sharp s to SS) str.upper applies: a\n")
out.append("// code point maps to the sequence it uppercases to, and a point absent here\n")
out.append("// uppercases to itself. Captured from the interpreter so it agrees with CPython\n")
out.append("// character for character.\n\n")
out.append("package runtime\n\n")
out.append("var ucdUpperFull = map[rune][]rune{\n")
for c in sorted(upper):
    lit = "{" + ", ".join("0x%X" % r for r in upper[c]) + "}"
    out.append("\t0x%X: %s,\n" % (c, lit))
out.append("}\n")

dst = os.path.join(os.path.dirname(__file__), "uppercase_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

subprocess.run(["gofmt", "-w", dst], check=True)
print("wrote %s: upper=%d" % (dst, len(upper)))
