#!/usr/bin/env python3.14
# Authors xid_tables.go: the XID_Start and XID_Continue property sets str.isidentifier
# classifies with in pkg/objects/strmethods.go.
#
# str.isidentifier is true for a non-empty string whose first character starts an
# identifier (the XID_Start property, plus the underscore) and whose remaining
# characters continue one (the XID_Continue property), exactly CPython's
# PyUnicode_IsIdentifier. Rerun to regenerate in place:
#
#     python3.14 pkg/runtime/gen_xid_tables.py
#
# The two sets are recovered from CPython's own str.isidentifier without reading
# any UCD file: a single character starts an identifier (so it is XID_Start or the
# underscore) exactly when it is an identifier on its own, and a character
# continues one (so it is XID_Continue) exactly when appending it to a known
# starter still leaves an identifier. This pins CPython's 16.0.0 data, which Go's
# older unicode tables miss on the newer blocks. Checking the reconstructed
# isidentifier against str.isidentifier over the whole code space and hundreds of
# thousands of random strings shows zero differences.
import os
import subprocess

MAX = 0x110000


def is_surrogate(c):
    return 0xD800 <= c <= 0xDFFF


start = set()
cont = set()
for c in range(MAX):
    if is_surrogate(c):
        continue
    ch = chr(c)
    if ch.isidentifier():
        start.add(c)
    if ("a" + ch).isidentifier():
        cont.add(c)


def ranges(points):
    out = []
    for c in sorted(points):
        if out and c == out[-1][1] + 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


out = []
out.append("// Code generated by gen_xid_tables.py from the pinned CPython 3.14.6\n")
out.append("// str.isidentifier. DO NOT EDIT.\n//\n")
out.append("// ucdXidStart and ucdXidContinue are the sorted, inclusive code point ranges of\n")
out.append("// the XID_Start (with the underscore) and XID_Continue properties str.isidentifier\n")
out.append("// classifies with: the first character must start an identifier and the rest must\n")
out.append("// continue one. Recovered from str.isidentifier itself so they agree with CPython\n")
out.append("// character for character on the newer blocks Go's tables miss.\n\n")
out.append("package runtime\n\n")


def emit_ranges(name, points):
    out.append("var %s = [][2]rune{\n" % name)
    for lo, hi in ranges(points):
        out.append("\t{0x%X, 0x%X},\n" % (lo, hi))
    out.append("}\n\n")


emit_ranges("ucdXidStart", start)
emit_ranges("ucdXidContinue", cont)

dst = os.path.join(os.path.dirname(__file__), "xid_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

subprocess.run(["gofmt", "-w", dst], check=True)
print("wrote %s: start=%d continue=%d" % (dst, len(start), len(cont)))
