# Regenerate pkg/runtime/codecs_jp_tables.go from the host CPython oracle.
#
# The Japanese codecs in this file are table-driven codecs the engine's generic
# mbTableCodec drives: some bytes decode on their own (ascii and half-width
# katakana), a lead byte 0x81..0x9F or 0xE0..0xFC selects a two-byte character,
# and everything else is illegal. We probe every standalone byte and every
# candidate pair through the oracle decoder, and we build the encoder from the
# oracle encoder so both directions are byte-exact against CPython 3.14.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_jp_tables.py
# then `gofmt -w pkg/runtime/codecs_jp_tables.go`.

CODECS = [("shift_jis", "shiftJIS"), ("cp932", "cp932")]


def build(codec):
    single = {}
    for b in range(256):
        try:
            s = bytes([b]).decode(codec)
        except UnicodeDecodeError:
            continue
        if len(s) != 1:
            raise SystemExit("%s: multi-char single byte %02x" % (codec, b))
        single[b] = ord(s)

    # The lead-byte set is decided by byte range, not by whether a mapping
    # exists: a byte in the lead range with no assigned character still reports
    # "incomplete multibyte sequence" when it stands alone (it wants a trail) and
    # "illegal multibyte sequence" once a trail follows. CPython's classification
    # of a lone byte tells us which bytes are leads, so we read the lead set off
    # that, and only the pairs that actually map go in the double table.
    leads = set()
    for b in range(256):
        if b in single:
            continue
        try:
            bytes([b]).decode(codec)
        except UnicodeDecodeError as e:
            if "incomplete" in str(e):
                leads.add(b)

    double = {}
    for lead in sorted(leads):
        for trail in range(256):
            try:
                s = bytes([lead, trail]).decode(codec)
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("%s: multi-char pair %02x%02x" % (codec, lead, trail))
            double[(lead, trail)] = ord(s)

    # Build the encoder straight from the oracle so a code point with more than
    # one decoding still encodes to CPython's canonical bytes. The encodable set
    # is the set of code points the decoder produces.
    enc_single = {}
    enc_double = {}
    for cp in sorted(set(single.values()) | set(double.values())):
        b = chr(cp).encode(codec)
        if len(b) == 1:
            enc_single[cp] = b[0]
        elif len(b) == 2:
            enc_double[cp] = (b[0] << 8) | b[1]
        else:
            raise SystemExit("%s: U+%04X encodes to %d bytes" % (codec, cp, len(b)))
    return single, sorted(leads), double, enc_single, enc_double


out = []
out.append("// Code generated by gen_codecs_jp_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// Japanese codec mapping tables, generated byte-exact from the CPython oracle")
out.append("// (host python3.14, the interpreter the conformance corpus records against).")
out.append("// Each codec is a table-driven mbTableCodec: standalone bytes, a lead-byte set,")
out.append("// the two-byte decode map, and the encode maps built from the oracle encoder.")
out.append("")
out.append("package runtime")

for codec, prefix in CODECS:
    single, leads, double, enc_single, enc_double = build(codec)
    out.append("")
    out.append("// %sSingleDecode maps each standalone byte (ascii and half-width" % prefix)
    out.append("// katakana) to its code point, %d entries." % len(single))
    out.append("var %sSingleDecode = map[byte]rune{" % prefix)
    for b in sorted(single):
        out.append("\t0x%02X: 0x%04X," % (b, single[b]))
    out.append("}")
    out.append("")
    out.append("// %sLeads lists the lead bytes that begin a two-byte character." % prefix)
    out.append("var %sLeads = []byte{%s}" % (prefix, ", ".join("0x%02X" % l for l in leads)))
    out.append("")
    out.append("// %sDoubleDecode maps a two-byte key (lead<<8 | trail) to its code" % prefix)
    out.append("// point, %d entries." % len(double))
    out.append("var %sDoubleDecode = map[uint16]rune{" % prefix)
    for (lead, trail) in sorted(double):
        out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, double[(lead, trail)]))
    out.append("}")
    out.append("")
    out.append("// %sSingleEncode maps a code point to its standalone byte, %d entries." % (prefix, len(enc_single)))
    out.append("var %sSingleEncode = map[rune]byte{" % prefix)
    for cp in sorted(enc_single):
        out.append("\t0x%04X: 0x%02X," % (cp, enc_single[cp]))
    out.append("}")
    out.append("")
    out.append("// %sDoubleEncode maps a code point to its two-byte value, %d entries." % (prefix, len(enc_double)))
    out.append("var %sDoubleEncode = map[rune]uint16{" % prefix)
    for cp in sorted(enc_double):
        out.append("\t0x%04X: 0x%04X," % (cp, enc_double[cp]))
    out.append("}")

out.append("")
open("pkg/runtime/codecs_jp_tables.go", "w").write("\n".join(out))
print("shift_jis tables written")
