#!/usr/bin/env python3.14
# Authors east_asian_width_tables.go: the East_Asian_Width property ranges
# unicodedata.east_asian_width answers from in unicodedatamod.go.
#
# east_asian_width returns one of the six width classes F, H, W, Na, A and N for
# a code point, the width the terminal and _pyrepl column math depend on. Rerun
# to regenerate in place:
#
#     python3.14 pkg/runtime/gen_east_asian_width_tables.py
#
# The ranges are read straight from CPython's unicodedata.east_asian_width so
# they carry its 16.0.0 data, including the halfwidth (H) and ambiguous (A)
# classes and the full narrow (Na) set the earlier hand-rolled version dropped.
# The Neutral (N) class is the lookup default, so only the other five classes are
# stored; a code point in no stored range is Neutral, matching CPython.
import os
import subprocess

MAX = 0x110000


def is_surrogate(c):
    return 0xD800 <= c <= 0xDFFF


import unicodedata as ud

ranges = []
for cp in range(MAX):
    w = "N" if is_surrogate(cp) else ud.east_asian_width(chr(cp))
    if ranges and ranges[-1][2] == w and cp == ranges[-1][1] + 1:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp, w])
ranges = [r for r in ranges if r[2] != "N"]

out = []
out.append("// Code generated by gen_east_asian_width_tables.py from the pinned CPython\n")
out.append("// 3.14.6 unicodedata.east_asian_width. DO NOT EDIT.\n//\n")
out.append("// ucdEastAsianWidthRanges are the sorted, inclusive code point ranges of the\n")
out.append("// East_Asian_Width classes other than Neutral (F fullwidth, H halfwidth, W wide,\n")
out.append("// Na narrow, A ambiguous). A code point in no stored range is Neutral (N), the\n")
out.append("// property's default, so east_asian_width looks a point up by binary search and\n")
out.append("// falls back to N.\n\n")
out.append("package runtime\n\n")
out.append("var ucdEastAsianWidthRanges = []eawRange{\n")
for lo, hi, w in ranges:
    out.append('\t{0x%X, 0x%X, "%s"},\n' % (lo, hi, w))
out.append("}\n")

dst = os.path.join(os.path.dirname(__file__), "east_asian_width_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

subprocess.run(["gofmt", "-w", dst], check=True)
print("wrote %s: ranges=%d" % (dst, len(ranges)))
