# Regenerate pkg/runtime/codecs_jp_sjis2004_tables.go from the host CPython oracle.
#
# shift_jis_2004 and shift_jisx0213 are the JIS X 0213 members of the shift_jis
# family: they share the fixed-width shift_jis byte structure (ascii and
# half-width katakana as single bytes, a lead byte plus a trail as a two-byte
# character) but a handful of two-byte sequences decode to a base plus a
# combining mark rather than a single code point, and the encoder combines a base
# and its mark back into that one sequence with a two-code-point lookahead. The
# fixed-width mbTableCodec drives them once its combining tables are attached.
#
# We probe every standalone byte and every candidate pair through the oracle
# decoder, splitting the pairs that decode to two code points into the combining
# table, and we build the encoder from the oracle encoder so both directions are
# byte-exact against CPython 3.14. The supplementary-plane code points (>0xFFFF)
# need no special handling: a Go rune already holds them.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_jp_sjis2004_tables.py
# then `gofmt -w pkg/runtime/codecs_jp_sjis2004_tables.go`.

CODECS = [("shift_jis_2004", "shiftJIS2004"), ("shift_jisx0213", "shiftJISX0213")]


def build(codec):
    single = {}
    for b in range(256):
        try:
            s = bytes([b]).decode(codec)
        except UnicodeDecodeError:
            continue
        if len(s) != 1:
            raise SystemExit("%s: multi-char single byte %02x" % (codec, b))
        single[b] = ord(s)

    # The lead set is decided by byte range: a lead-range byte with no assigned
    # character reports "incomplete" alone and "illegal" once a trail follows, so
    # read the lead set off CPython's classification of a lone byte.
    leads = set()
    for b in range(256):
        if b in single:
            continue
        try:
            bytes([b]).decode(codec)
        except UnicodeDecodeError as e:
            if "incomplete" in str(e):
                leads.add(b)

    double = {}
    multi = {}
    for lead in sorted(leads):
        for trail in range(256):
            try:
                s = bytes([lead, trail]).decode(codec)
            except UnicodeDecodeError:
                continue
            if len(s) == 1:
                double[(lead, trail)] = ord(s)
            elif len(s) == 2:
                multi[(lead, trail)] = (ord(s[0]), ord(s[1]))
            else:
                raise SystemExit("%s: %d-char pair %02x%02x" % (codec, len(s), lead, trail))

    # Build the single-code-point encoder from the oracle so a code point with
    # more than one decoding still encodes to CPython's canonical bytes.
    enc_single = {}
    enc_double = {}
    for cp in sorted(set(single.values()) | set(double.values())):
        b = chr(cp).encode(codec)
        if len(b) == 1:
            enc_single[cp] = b[0]
        elif len(b) == 2:
            enc_double[cp] = (b[0] << 8) | b[1]
        else:
            raise SystemExit("%s: U+%04X encodes to %d bytes" % (codec, cp, len(b)))

    # The pair encoder maps a (base, mark) code-point pair to the two bytes the
    # oracle emits for it, and the base set is every code point that can begin
    # such a pair (what the incremental encoder holds pending across a chunk).
    enc_pair = {}
    bases = set()
    for (a, b) in multi.values():
        e = (chr(a) + chr(b)).encode(codec)
        if len(e) != 2:
            raise SystemExit("%s: pair U+%04X U+%04X encodes to %d bytes" % (codec, a, b, len(e)))
        enc_pair[(a, b)] = (e[0] << 8) | e[1]
        bases.add(a)
    return single, sorted(leads), double, multi, enc_single, enc_double, enc_pair, sorted(bases)


out = []
out.append("// Code generated by gen_codecs_jp_sjis2004_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// JIS X 0213 shift_jis mapping tables, generated byte-exact from the CPython")
out.append("// oracle (host python3.14, the interpreter the conformance corpus records")
out.append("// against). Each codec is a fixed-width mbTableCodec with combining tables: a")
out.append("// few two-byte sequences decode to a base plus a combining mark, and the encoder")
out.append("// combines a base and its mark back with a two-code-point lookahead.")
out.append("")
out.append("package runtime")

for codec, prefix in CODECS:
    single, leads, double, multi, enc_single, enc_double, enc_pair, bases = build(codec)
    out.append("")
    out.append("// %sSingleDecode maps each standalone byte (ascii and half-width" % prefix)
    out.append("// katakana) to its code point, %d entries." % len(single))
    out.append("var %sSingleDecode = map[byte]rune{" % prefix)
    for b in sorted(single):
        out.append("\t0x%02X: 0x%04X," % (b, single[b]))
    out.append("}")
    out.append("")
    out.append("// %sLeads lists the lead bytes that begin a two-byte character." % prefix)
    out.append("var %sLeads = []byte{%s}" % (prefix, ", ".join("0x%02X" % l for l in leads)))
    out.append("")
    out.append("// %sDoubleDecode maps a two-byte key (lead<<8 | trail) to its single code" % prefix)
    out.append("// point, %d entries." % len(double))
    out.append("var %sDoubleDecode = map[uint16]rune{" % prefix)
    for (lead, trail) in sorted(double):
        out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, double[(lead, trail)]))
    out.append("}")
    out.append("")
    out.append("// %sMultiDecode maps a two-byte key to the base and combining mark it" % prefix)
    out.append("// decodes to, the %d JIS X 0213 combining sequences." % len(multi))
    out.append("var %sMultiDecode = map[uint16][2]rune{" % prefix)
    for (lead, trail) in sorted(multi):
        a, b = multi[(lead, trail)]
        out.append("\t0x%04X: {0x%04X, 0x%04X}," % ((lead << 8) | trail, a, b))
    out.append("}")
    out.append("")
    out.append("// %sSingleEncode maps a code point to its standalone byte, %d entries." % (prefix, len(enc_single)))
    out.append("var %sSingleEncode = map[rune]byte{" % prefix)
    for cp in sorted(enc_single):
        out.append("\t0x%04X: 0x%02X," % (cp, enc_single[cp]))
    out.append("}")
    out.append("")
    out.append("// %sDoubleEncode maps a code point to its two-byte value, %d entries." % (prefix, len(enc_double)))
    out.append("var %sDoubleEncode = map[rune]uint16{" % prefix)
    for cp in sorted(enc_double):
        out.append("\t0x%04X: 0x%04X," % (cp, enc_double[cp]))
    out.append("}")
    out.append("")
    out.append("// %sPairEncode maps a (base, mark) code-point pair to its two-byte value," % prefix)
    out.append("// the %d combining sequences the encoder folds with a lookahead." % len(enc_pair))
    out.append("var %sPairEncode = map[[2]rune]uint16{" % prefix)
    for (a, b) in sorted(enc_pair):
        out.append("\t{0x%04X, 0x%04X}: 0x%04X," % (a, b, enc_pair[(a, b)]))
    out.append("}")
    out.append("")
    out.append("// %sBases lists the code points that can begin a combining pair, held" % prefix)
    out.append("// pending by the incremental encoder across a chunk boundary.")
    out.append("var %sBases = []rune{%s}" % (prefix, ", ".join("0x%04X" % r for r in bases)))

out.append("")
open("pkg/runtime/codecs_jp_sjis2004_tables.go", "w").write("\n".join(out))
print("shift_jis_2004 / shift_jisx0213 tables written")
