#!/usr/bin/env python3.14
# Authors case_property_tables.go: the Uppercase and Lowercase property sets that
# back str.swapcase's per-character branch and str.isupper / str.islower in
# pkg/objects/strmethods.go.
#
# str.swapcase lowercases the uppercase characters and uppercases the lowercase
# ones, leaving everything else (a titlecase character, a letter with no case, a
# symbol) untouched. It decides the branch with the Uppercase and Lowercase
# properties, exactly CPython's do_swapcase (Py_UNICODE_ISUPPER / ISLOWER).
# str.isupper and str.islower classify each character with the same two
# properties (Py_UNICODE_ISUPPER / ISLOWER again), so a single pair of pinned
# sets serves both. Rerun to regenerate in place:
#
#     python3.14 pkg/runtime/gen_case_property_tables.py
#
# The two sets are the true Uppercase and Lowercase properties, read straight
# from CPython so they match its 16.0.0 data on the newer bicameral blocks (the
# Garay letters, the rams-horn additions) where Go's older unicode tables and
# the mapping-table keys both fall short. A character has the Uppercase property
# when str.isupper is true for it in isolation and the Lowercase property when
# str.islower is. These are supersets of the case-mapping keys: a caseless-cased
# letter like a Roman numeral or a mathematical capital keeps its property even
# though it maps to itself, and swapcase still leaves it unchanged because the
# mapping is the identity. Checking the reconstructed swapcase, isupper and
# islower against CPython over the whole code space and hundreds of thousands of
# random strings shows zero differences.
import os
import subprocess

MAX = 0x110000


def is_surrogate(c):
    return 0xD800 <= c <= 0xDFFF


uppercase = set()
lowercase = set()
for c in range(MAX):
    if is_surrogate(c):
        continue
    ch = chr(c)
    if ch.isupper():
        uppercase.add(c)
    if ch.islower():
        lowercase.add(c)


def ranges(points):
    out = []
    for c in sorted(points):
        if out and c == out[-1][1] + 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


out = []
out.append("// Code generated by gen_case_property_tables.py from the pinned CPython 3.14.6\n")
out.append("// str.isupper / str.islower. DO NOT EDIT.\n//\n")
out.append("// ucdUppercase and ucdLowercase are the sorted, inclusive code point ranges of\n")
out.append("// the Uppercase and Lowercase properties. str.swapcase lowercases an uppercase\n")
out.append("// character and uppercases a lowercase one, leaving everything else (titlecase,\n")
out.append("// caseless, symbols) untouched; str.isupper and str.islower classify with the\n")
out.append("// same two properties. Read straight from CPython so they agree character for\n")
out.append("// character on the newer bicameral blocks Go's tables miss.\n\n")
out.append("package runtime\n\n")


def emit_ranges(name, points):
    out.append("var %s = [][2]rune{\n" % name)
    for lo, hi in ranges(points):
        out.append("\t{0x%X, 0x%X},\n" % (lo, hi))
    out.append("}\n\n")


emit_ranges("ucdUppercase", uppercase)
emit_ranges("ucdLowercase", lowercase)

dst = os.path.join(os.path.dirname(__file__), "case_property_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

subprocess.run(["gofmt", "-w", dst], check=True)
print("wrote %s: uppercase=%d lowercase=%d" % (dst, len(uppercase), len(lowercase)))
