# Regenerate pkg/runtime/codecs_jp_euc2004_tables.go from the host CPython oracle.
#
# euc_jis_2004 and euc_jisx0213 are the JIS X 0213 members of the euc_jp family:
# they share the variable-width euc_jp byte structure (ascii single bytes, 0x8e
# plus one byte for half-width katakana, 0x8f plus two bytes for the plane 2
# character, any other high byte a two-byte lead) but a handful of two-byte
# sequences in the double space decode to a base plus a combining mark rather than
# a single code point, and the encoder folds a base and its mark back into that
# one sequence with a two-code-point lookahead. The 0x8f three-byte space carries
# no combining sequences. The variable-width mbEUCJPCodec drives them once its
# combining tables are attached.
#
# We probe every candidate sequence through the oracle decoder, splitting the
# two-byte pairs that decode to two code points into the combining table, and we
# build the encoder from the oracle encoder so both directions are byte-exact
# against CPython 3.14.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_jp_euc2004_tables.py
# then `gofmt -w pkg/runtime/codecs_jp_euc2004_tables.go`.

CODECS = [("euc_jis_2004", "eucJIS2004"), ("euc_jisx0213", "eucJISX0213")]
SS3 = 0x8F


def build(codec):
    leads = []
    for b in range(0x80, 0x100):
        try:
            bytes([b]).decode(codec)
        except UnicodeDecodeError as e:
            if "incomplete" in str(e):
                leads.append(b)

    double = {}
    multi = {}
    for lead in leads:
        if lead == SS3:
            continue
        for trail in range(256):
            try:
                s = bytes([lead, trail]).decode(codec)
            except UnicodeDecodeError:
                continue
            if len(s) == 1:
                double[(lead, trail)] = ord(s)
            elif len(s) == 2:
                multi[(lead, trail)] = (ord(s[0]), ord(s[1]))
            else:
                raise SystemExit("%s: %d-char pair %02x%02x" % (codec, len(s), lead, trail))

    triple = {}
    for b2 in range(256):
        for b3 in range(256):
            try:
                s = bytes([SS3, b2, b3]).decode(codec)
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("%s: %d-char triple 8f%02x%02x" % (codec, len(s), b2, b3))
            triple[(b2, b3)] = ord(s)

    # A few code points decode but do not encode back (CPython maps them from
    # bytes yet has no canonical bytes for them, so encoding them raises); skip
    # those so the encode map holds only what the oracle can actually encode.
    enc_double = {}
    enc_triple = {}
    for cp in sorted(set(double.values()) | set(triple.values())):
        if cp < 0x80:
            continue
        try:
            b = chr(cp).encode(codec)
        except UnicodeEncodeError:
            continue
        if len(b) == 2:
            enc_double[cp] = (b[0] << 8) | b[1]
        elif len(b) == 3:
            if b[0] != SS3:
                raise SystemExit("%s: U+%04X three-byte but not SS3" % (codec, cp))
            enc_triple[cp] = (b[1] << 8) | b[2]
        else:
            raise SystemExit("%s: U+%04X encodes to %d bytes" % (codec, cp, len(b)))

    # The pair encoder maps a (base, mark) code-point pair to its two bytes in the
    # double space, and the base set is every code point that can begin such a
    # pair (what the incremental encoder holds pending across a chunk).
    enc_pair = {}
    bases = set()
    for (a, b) in multi.values():
        e = (chr(a) + chr(b)).encode(codec)
        if len(e) != 2:
            raise SystemExit("%s: pair U+%04X U+%04X encodes to %d bytes" % (codec, a, b, len(e)))
        enc_pair[(a, b)] = (e[0] << 8) | e[1]
        bases.add(a)
    return sorted(leads), double, multi, triple, enc_double, enc_triple, enc_pair, sorted(bases)


out = []
out.append("// Code generated by gen_codecs_jp_euc2004_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// JIS X 0213 euc mapping tables, generated byte-exact from the CPython oracle")
out.append("// (host python3.14, the interpreter the conformance corpus records against).")
out.append("// Each codec is a variable-width mbEUCJPCodec with combining tables: a few")
out.append("// two-byte sequences decode to a base plus a combining mark, and the encoder")
out.append("// folds a base and its mark back with a two-code-point lookahead.")
out.append("")
out.append("package runtime")

for codec, prefix in CODECS:
    leads, double, multi, triple, enc_double, enc_triple, enc_pair, bases = build(codec)
    out.append("")
    out.append("// %sLeads lists every byte that begins a multibyte sequence (0x8e and 0x8f" % prefix)
    out.append("// included); a lone lead is incomplete and a bad trail is illegal.")
    out.append("var %sLeads = []byte{%s}" % (prefix, ", ".join("0x%02X" % l for l in leads)))
    out.append("")
    out.append("// %sDoubleDecode maps a two-byte key (lead<<8 | trail) to its single code" % prefix)
    out.append("// point, %d entries." % len(double))
    out.append("var %sDoubleDecode = map[uint16]rune{" % prefix)
    for (lead, trail) in sorted(double):
        out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, double[(lead, trail)]))
    out.append("}")
    out.append("")
    out.append("// %sMultiDecode maps a two-byte key to the base and combining mark it" % prefix)
    out.append("// decodes to, the %d JIS X 0213 combining sequences." % len(multi))
    out.append("var %sMultiDecode = map[uint16][2]rune{" % prefix)
    for (lead, trail) in sorted(multi):
        a, b = multi[(lead, trail)]
        out.append("\t0x%04X: {0x%04X, 0x%04X}," % ((lead << 8) | trail, a, b))
    out.append("}")
    out.append("")
    out.append("// %sTripleDecode maps the two bytes after 0x8f (b2<<8 | b3) to their code" % prefix)
    out.append("// point, %d entries." % len(triple))
    out.append("var %sTripleDecode = map[uint16]rune{" % prefix)
    for (b2, b3) in sorted(triple):
        out.append("\t0x%04X: 0x%04X," % ((b2 << 8) | b3, triple[(b2, b3)]))
    out.append("}")
    out.append("")
    out.append("// %sDoubleEncode maps a code point to its two-byte value, %d entries." % (prefix, len(enc_double)))
    out.append("var %sDoubleEncode = map[rune]uint16{" % prefix)
    for cp in sorted(enc_double):
        out.append("\t0x%04X: 0x%04X," % (cp, enc_double[cp]))
    out.append("}")
    out.append("")
    out.append("// %sTripleEncode maps a code point to the two bytes that follow 0x8f, %d" % (prefix, len(enc_triple)))
    out.append("// entries.")
    out.append("var %sTripleEncode = map[rune]uint16{" % prefix)
    for cp in sorted(enc_triple):
        out.append("\t0x%04X: 0x%04X," % (cp, enc_triple[cp]))
    out.append("}")
    out.append("")
    out.append("// %sPairEncode maps a (base, mark) code-point pair to its two-byte value," % prefix)
    out.append("// the %d combining sequences the encoder folds with a lookahead." % len(enc_pair))
    out.append("var %sPairEncode = map[[2]rune]uint16{" % prefix)
    for (a, b) in sorted(enc_pair):
        out.append("\t{0x%04X, 0x%04X}: 0x%04X," % (a, b, enc_pair[(a, b)]))
    out.append("}")
    out.append("")
    out.append("// %sBases lists the code points that can begin a combining pair, held" % prefix)
    out.append("// pending by the incremental encoder across a chunk boundary.")
    out.append("var %sBases = []rune{%s}" % (prefix, ", ".join("0x%04X" % r for r in bases)))

out.append("")
open("pkg/runtime/codecs_jp_euc2004_tables.go", "w").write("\n".join(out))
print("euc_jis_2004 / euc_jisx0213 tables written")
