#!/usr/bin/env python3.14
# Authors unicodedata_tables.go: the canonical and compatibility decomposition
# mappings, the canonical combining classes, and the canonical composition pairs
# that back unicodedata.normalize / is_normalized in pkg/runtime/unicodedatamod.go.
#
# The tables are captured straight from the pinned python3.14's own unicodedata
# module (the conformance oracle), never hand-written, so they agree with CPython
# character for character. Go's stdlib carries UCD 15.0.0; CPython 3.14.6 carries
# 16.0.0, which is exactly why these cannot be composed from Go's unicode package
# and must be pinned from the interpreter. Rerun to regenerate the file in place:
#
#     python3.14 pkg/runtime/gen_unicodedata_tables.py
#
# Hangul syllables (U+AC00..U+D7A3) are decomposed and composed arithmetically by
# the algorithm in unicodedatamod.go (UAX #15 section on Hangul), so they are
# deliberately excluded from every table here.
import os
import subprocess
import unicodedata as ud

MAX = 0x110000
HANGUL_LO, HANGUL_HI = 0xAC00, 0xD7A3


def is_hangul(c):
    return HANGUL_LO <= c <= HANGUL_HI


# Full (recursive) decompositions come straight from NFD/NFKD of the single
# character, which is fully decomposed and canonically ordered by construction;
# an entry is stored only when the form actually changes the character. The Go
# side looks these up without recursing, so they must be the full mapping.
canon, compat, ccc, decomp = {}, {}, {}, {}
for c in range(MAX):
    if is_hangul(c):
        continue
    ch = chr(c)
    d = ud.normalize("NFD", ch)
    if d != ch:
        canon[c] = [ord(x) for x in d]
    k = ud.normalize("NFKD", ch)
    if k != ch:
        compat[c] = [ord(x) for x in k]
    cc = ud.combining(ch)
    if cc:
        ccc[c] = cc
    # The raw one-level decomposition string (with its <tag>, if any) is what
    # unicodedata.decomposition returns verbatim; capture it as-is. Hangul
    # syllables also have a value here but are formatted arithmetically in Go.
    ds = ud.decomposition(ch)
    if ds:
        decomp[c] = ds

# Composition pairs are the raw one-level canonical (untagged) decompositions of
# length two, kept only when NFC actually recomposes them. Testing against NFC
# honours the Composition Exclusion table and the non-starter/singleton rules for
# free, so a pair lands here iff canonical composition would fold it back.
comp = {}
for c in range(MAX):
    if is_hangul(c):
        continue
    ds = ud.decomposition(chr(c))
    if not ds or ds.startswith("<"):
        continue
    p = ds.split()
    if len(p) != 2:
        continue
    a, b = int(p[0], 16), int(p[1], 16)
    if is_hangul(a) or is_hangul(b):
        continue
    if ud.normalize("NFC", chr(a) + chr(b)) == chr(c):
        comp[(a, b)] = c

# The numeric properties (decimal, digit, numeric) and the Bidi_Mirrored flag are
# UCD data Go's `unicode` package does not carry, so they are pinned from the
# oracle across the whole code space. decimal/digit are ints and numeric is a
# float, exactly as CPython returns them; an entry is stored only where the
# property is defined, so a lookup miss reproduces the ValueError CPython raises.
decimalv, digitv, numericv, mirrored = {}, {}, {}, []
for c in range(MAX):
    ch = chr(c)
    dv = ud.decimal(ch, None)
    if dv is not None:
        decimalv[c] = dv
    gv = ud.digit(ch, None)
    if gv is not None:
        digitv[c] = gv
    nv = ud.numeric(ch, None)
    if nv is not None:
        numericv[c] = nv
    if ud.mirrored(ch):
        mirrored.append(c)

# The Bidi_Class property compresses into contiguous ranges (most of the code
# space shares a run of one class), so it is stored as sorted [lo, hi] ranges
# rather than a per-character map. Only the ranges with a non-empty class are
# kept; a code point outside every stored range has no bidi class, which is the
# "" CPython returns for it.
bidi = []
start = 0
cur = ud.bidirectional(chr(0))
for c in range(1, MAX + 1):
    b = ud.bidirectional(chr(c)) if c < MAX else None
    if b != cur:
        if cur != "":
            bidi.append((start, c - 1, cur))
        start, cur = c, b

out = []
out.append("// Code generated by gen_unicodedata_tables.py from the pinned CPython 3.14.6\n")
out.append("// unicodedata (Unicode Character Database %s). DO NOT EDIT.\n//\n" % ud.unidata_version)
out.append("// The canonical and compatibility decomposition mappings, canonical combining\n")
out.append("// classes, and canonical composition pairs behind unicodedata.normalize, plus the\n")
out.append("// decimal/digit/numeric values, the Bidi_Mirrored flag and the Bidi_Class ranges.\n")
out.append("// Hangul syllables are handled arithmetically in unicodedatamod.go and are absent\n")
out.append("// from the decomposition tables here.\n\n")
out.append("package runtime\n\n")


def runes_lit(rs):
    return "{" + ", ".join("0x%X" % r for r in rs) + "}"


def emit_decomp(name, m):
    out.append("var %s = map[rune][]rune{\n" % name)
    for c in sorted(m):
        out.append("\t0x%X: %s,\n" % (c, runes_lit(m[c])))
    out.append("}\n\n")


emit_decomp("ucdCanonDecomp", canon)
emit_decomp("ucdCompatDecomp", compat)

out.append("var ucdCombiningClass = map[rune]uint8{\n")
for c in sorted(ccc):
    out.append("\t0x%X: %d,\n" % (c, ccc[c]))
out.append("}\n\n")

out.append("var ucdComposePair = map[[2]rune]rune{\n")
for (a, b) in sorted(comp):
    out.append("\t{0x%X, 0x%X}: 0x%X,\n" % (a, b, comp[(a, b)]))
out.append("}\n\n")

out.append("var ucdDecomposition = map[rune]string{\n")
for c in sorted(decomp):
    # Every value is safe ASCII (hex digits, spaces, and an angle-bracketed
    # tag), so a plain Go double-quoted literal is exact.
    out.append('\t0x%X: "%s",\n' % (c, decomp[c]))
out.append("}\n\n")

out.append("var ucdDecimal = map[rune]int{\n")
for c in sorted(decimalv):
    out.append("\t0x%X: %d,\n" % (c, decimalv[c]))
out.append("}\n\n")

out.append("var ucdDigit = map[rune]int{\n")
for c in sorted(digitv):
    out.append("\t0x%X: %d,\n" % (c, digitv[c]))
out.append("}\n\n")

out.append("var ucdNumeric = map[rune]float64{\n")
for c in sorted(numericv):
    # repr of a Python float is a round-trippable literal Go parses exactly
    # (0.5, 0.3333333333333333, 1e+16), and numeric() always returns a float, so
    # the stored value is the same float CPython hands back.
    out.append("\t0x%X: %r,\n" % (c, numericv[c]))
out.append("}\n\n")

out.append("var ucdMirrored = map[rune]bool{\n")
for c in mirrored:
    out.append("\t0x%X: true,\n" % c)
out.append("}\n\n")

out.append("var ucdBidiRanges = []bidiRange{\n")
for lo, hi, cl in bidi:
    out.append('\t{0x%X, 0x%X, "%s"},\n' % (lo, hi, cl))
out.append("}\n")

dst = os.path.join(os.path.dirname(__file__), "unicodedata_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

# gofmt aligns map-literal values within contiguous runs; run it so the emitted
# file is byte-identical to what a reviewer's editor would produce and the repo
# stays gofmt-clean without a manual pass.
subprocess.run(["gofmt", "-w", dst], check=True)

print(
    "wrote %s: canon=%d compat=%d ccc=%d comp=%d decimal=%d digit=%d numeric=%d mirrored=%d bidi=%d"
    % (
        dst, len(canon), len(compat), len(ccc), len(comp),
        len(decimalv), len(digitv), len(numericv), len(mirrored), len(bidi),
    )
)
