# Regenerate pkg/runtime/codecs_tw_tables.go from the host CPython oracle.
#
# The Taiwanese codecs in this file are fixed-width two-byte table codecs the
# engine's generic mbTableCodec drives: ascii decodes on its own, a lead byte
# selects a two-byte character, and everything else is illegal. big5 is the
# Taiwanese standard and cp950 is Microsoft's variant with a few extra rows. We
# probe every standalone byte and every candidate pair through the oracle
# decoder, and we build the encoder from the oracle encoder so both directions
# are byte-exact against CPython 3.14.
#
# The lead-byte set is decided by byte range, not by whether a mapping exists: a
# byte in the lead range with no assigned character still reports "incomplete
# multibyte sequence" when it stands alone and "illegal multibyte sequence" once
# a trail follows, so we read the lead set off CPython's classification of a lone
# byte rather than off the pairs that map.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_tw_tables.py
# then `gofmt -w pkg/runtime/codecs_tw_tables.go`.

CODECS = [("big5", "big5"), ("cp950", "cp950")]


def build(codec):
    single = {}
    for b in range(256):
        try:
            s = bytes([b]).decode(codec)
        except UnicodeDecodeError:
            continue
        if len(s) != 1:
            raise SystemExit("%s: multi-char single byte %02x" % (codec, b))
        single[b] = ord(s)

    leads = set()
    for b in range(256):
        if b in single:
            continue
        try:
            bytes([b]).decode(codec)
        except UnicodeDecodeError as e:
            if "incomplete" in str(e):
                leads.add(b)

    double = {}
    for lead in sorted(leads):
        for trail in range(256):
            try:
                s = bytes([lead, trail]).decode(codec)
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("%s: multi-char pair %02x%02x" % (codec, lead, trail))
            double[(lead, trail)] = ord(s)

    enc_single = {}
    enc_double = {}
    for cp in sorted(set(single.values()) | set(double.values())):
        b = chr(cp).encode(codec)
        if len(b) == 1:
            enc_single[cp] = b[0]
        elif len(b) == 2:
            enc_double[cp] = (b[0] << 8) | b[1]
        else:
            raise SystemExit("%s: U+%04X encodes to %d bytes" % (codec, cp, len(b)))
    return single, sorted(leads), double, enc_single, enc_double


out = []
out.append("// Code generated by gen_codecs_tw_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// Taiwanese codec mapping tables, generated byte-exact from the CPython oracle")
out.append("// (host python3.14, the interpreter the conformance corpus records against).")
out.append("// Each codec is a fixed-width two-byte mbTableCodec: standalone bytes, a")
out.append("// lead-byte set, the two-byte decode map, and the encode maps built from the")
out.append("// oracle encoder.")
out.append("")
out.append("package runtime")

for codec, prefix in CODECS:
    single, leads, double, enc_single, enc_double = build(codec)
    out.append("")
    out.append("// %sSingleDecode maps each standalone byte to its code point, %d entries." % (prefix, len(single)))
    out.append("var %sSingleDecode = map[byte]rune{" % prefix)
    for b in sorted(single):
        out.append("\t0x%02X: 0x%04X," % (b, single[b]))
    out.append("}")
    out.append("")
    out.append("// %sLeads lists the lead bytes that begin a two-byte character." % prefix)
    out.append("var %sLeads = []byte{%s}" % (prefix, ", ".join("0x%02X" % l for l in leads)))
    out.append("")
    out.append("// %sDoubleDecode maps a two-byte key (lead<<8 | trail) to its code" % prefix)
    out.append("// point, %d entries." % len(double))
    out.append("var %sDoubleDecode = map[uint16]rune{" % prefix)
    for (lead, trail) in sorted(double):
        out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, double[(lead, trail)]))
    out.append("}")
    out.append("")
    out.append("// %sSingleEncode maps a code point to its standalone byte, %d entries." % (prefix, len(enc_single)))
    out.append("var %sSingleEncode = map[rune]byte{" % prefix)
    for cp in sorted(enc_single):
        out.append("\t0x%04X: 0x%02X," % (cp, enc_single[cp]))
    out.append("}")
    out.append("")
    out.append("// %sDoubleEncode maps a code point to its two-byte value, %d entries." % (prefix, len(enc_double)))
    out.append("var %sDoubleEncode = map[rune]uint16{" % prefix)
    for cp in sorted(enc_double):
        out.append("\t0x%04X: 0x%04X," % (cp, enc_double[cp]))
    out.append("}")

out.append("")
open("pkg/runtime/codecs_tw_tables.go", "w").write("\n".join(out))
print("taiwanese tables written")
