# Regenerate pkg/runtime/codecs_iso2022_jp1_tables.go from the host CPython oracle.
#
# iso2022_jp_1 is iso2022_jp plus JIS X 0212, designated by ESC$(D. Everything else
# (ascii, JIS X 0201 roman, JIS X 0208) is shared with iso2022_jp and its tables, so
# the one extra table this variant needs is JIS X 0212: the GL byte pair
# (0x21..0x7e each) to its code point and back. We probe every pair through the
# oracle decoder and build the encoder from the oracle encoder so both directions
# are byte-exact against CPython 3.14.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_iso2022_jp1_tables.py
# then `gofmt -w pkg/runtime/codecs_iso2022_jp1_tables.go`.

ESC_0212 = b"\x1b$(D"


def build():
    decode = {}
    for lead in range(0x21, 0x7F):
        for trail in range(0x21, 0x7F):
            try:
                s = (ESC_0212 + bytes([lead, trail])).decode("iso2022_jp_1")
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                raise SystemExit("multi-char pair %02x%02x" % (lead, trail))
            decode[(lead, trail)] = ord(s)

    encode = {}
    for (lead, trail), cp in decode.items():
        b = chr(cp).encode("iso2022_jp_1")
        # A JIS X 0212 character encodes as ESC$(D <lead> <trail> ESC(B; pull the two
        # GL bytes back out and keep the canonical pair for each code point. A code
        # point also in JIS X 0208 encodes through ESC$B instead, so it is not a
        # JIS X 0212 encode entry.
        if not (b.startswith(ESC_0212) and b.endswith(b"\x1b(B")):
            continue
        pair = b[len(ESC_0212):-3]
        if len(pair) != 2:
            raise SystemExit("U+%04X encodes to %r" % (cp, b))
        encode.setdefault(cp, (pair[0], pair[1]))
    return decode, encode


decode, encode = build()

out = []
out.append("// Code generated by gen_codecs_iso2022_jp1_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// JIS X 0212 mapping tables for iso2022_jp_1, generated byte-exact from the CPython")
out.append("// oracle (host python3.14, the interpreter the conformance corpus records")
out.append("// against). The key is the GL byte pair (lead<<8 | trail), each byte 0x21..0x7e.")
out.append("")
out.append("package runtime")
out.append("")
out.append("// iso2022JISX0212Decode maps a JIS X 0212 GL pair to its code point, %d entries." % len(decode))
out.append("var iso2022JISX0212Decode = map[uint16]rune{")
for (lead, trail) in sorted(decode):
    out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, decode[(lead, trail)]))
out.append("}")
out.append("")
out.append("// iso2022JISX0212Encode maps a code point to its JIS X 0212 GL pair, %d entries." % len(encode))
out.append("var iso2022JISX0212Encode = map[rune]uint16{")
for cp in sorted(encode):
    lead, trail = encode[cp]
    out.append("\t0x%04X: 0x%04X," % (cp, (lead << 8) | trail))
out.append("}")
out.append("")
open("pkg/runtime/codecs_iso2022_jp1_tables.go", "w").write("\n".join(out))
print("iso2022_jp_1 tables written: %d decode, %d encode" % (len(decode), len(encode)))
