# Regenerate pkg/runtime/codecs_iso2022_jp3_tables.go from the host CPython oracle.
#
# iso2022_jp_3 is iso2022_jp plus the two JIS X 0213 planes: plane 1 designated by
# ESC$(O and plane 2 by ESC$(P. Plane 1 carries 25 combining sequences (a GL pair
# that decodes to a base plus a combining mark, U+309A); plane 2 has none. Some
# plane pairs are decode-only (no encode form), and a character also in JIS X 0208
# encodes through ESC$B instead, so a plane's encode map holds only the code points
# CPython actually routes through that plane. We probe every pair through the oracle
# decoder and build the encode maps from the oracle encoder so both directions are
# byte-exact against CPython 3.14.
#
# The generator asserts the plane encode maps do not overlap the shared JIS X 0208
# encode map, which is what lets the codec try 0208 before the planes in encode
# order without ever masking a plane character.
#
# Run from the repo root with the interpreter the conformance corpus uses:
#     python3.14 pkg/runtime/gen_codecs_iso2022_jp3_tables.py
# then `gofmt -w pkg/runtime/codecs_iso2022_jp3_tables.go`.

CODEC = "iso2022_jp_3"
ESC_P1 = b"\x1b$(O"
ESC_P2 = b"\x1b$(P"
ESC_ASCII = b"\x1b(B"


def scan_plane(esc):
    # decode: single-rune pairs; decode2: combining (two-rune) pairs.
    decode = {}
    decode2 = {}
    for lead in range(0x21, 0x7F):
        for trail in range(0x21, 0x7F):
            try:
                s = (esc + bytes([lead, trail]) + ESC_ASCII).decode(CODEC)
            except UnicodeDecodeError:
                continue
            if len(s) == 1:
                decode[(lead, trail)] = ord(s)
            elif len(s) == 2:
                decode2[(lead, trail)] = (ord(s[0]), ord(s[1]))
            else:
                raise SystemExit("pair %02x%02x -> %r" % (lead, trail, s))
    return decode, decode2


def build_encode(esc, decode, decode2):
    # A plane encode entry exists only when CPython routes that code point (or
    # combining sequence) through this plane's escape.
    encode = {}
    encode2 = {}
    for (lead, trail), cp in decode.items():
        try:
            b = chr(cp).encode(CODEC)
        except UnicodeEncodeError:
            continue
        if b.startswith(esc) and b.endswith(ESC_ASCII) and b[len(esc):-3] == bytes([lead, trail]):
            encode.setdefault(cp, (lead, trail))
    for (lead, trail), (a, c) in decode2.items():
        try:
            b = (chr(a) + chr(c)).encode(CODEC)
        except UnicodeEncodeError:
            continue
        if b.startswith(esc) and b.endswith(ESC_ASCII) and b[len(esc):-3] == bytes([lead, trail]):
            encode2.setdefault((a, c), (lead, trail))
    return encode, encode2


# The shared JIS X 0208 encode map, so we can assert the planes never overlap it.
jisx0208 = set()
for lead in range(0x21, 0x7F):
    for trail in range(0x21, 0x7F):
        try:
            s = (b"\x1b$B" + bytes([lead, trail]) + ESC_ASCII).decode("iso2022_jp")
        except UnicodeDecodeError:
            continue
        if len(s) == 1:
            b = chr(ord(s)).encode("iso2022_jp")
            if b.startswith(b"\x1b$B"):
                jisx0208.add(ord(s))

p1_dec, p1_dec2 = scan_plane(ESC_P1)
p2_dec, p2_dec2 = scan_plane(ESC_P2)
if p2_dec2:
    raise SystemExit("plane 2 unexpectedly has combining pairs")
p1_enc, p1_enc2 = build_encode(ESC_P1, p1_dec, p1_dec2)
p2_enc, _ = build_encode(ESC_P2, p2_dec, {})

overlap = (set(p1_enc) | set(p2_enc)) & jisx0208
if overlap:
    raise SystemExit("plane encode overlaps JIS X 0208: %r" % sorted(overlap)[:8])

base = sorted({a for (a, _c) in p1_enc2})


def emit_decode(name, dec, desc):
    out = []
    out.append("// %s maps a JIS X 0213 %s GL pair to its code point, %d entries." % (name, desc, len(dec)))
    out.append("var %s = map[uint16]rune{" % name)
    for (lead, trail) in sorted(dec):
        out.append("\t0x%04X: 0x%04X," % ((lead << 8) | trail, dec[(lead, trail)]))
    out.append("}")
    out.append("")
    return out


def emit_encode(name, enc, desc):
    out = []
    out.append("// %s maps a code point to its JIS X 0213 %s GL pair, %d entries." % (name, desc, len(enc)))
    out.append("var %s = map[rune]uint16{" % name)
    for cp in sorted(enc):
        lead, trail = enc[cp]
        out.append("\t0x%04X: 0x%04X," % (cp, (lead << 8) | trail))
    out.append("}")
    out.append("")
    return out


out = []
out.append("// Code generated by gen_codecs_iso2022_jp3_tables.py. DO NOT EDIT.")
out.append("//")
out.append("// JIS X 0213 plane 1 (ESC$(O) and plane 2 (ESC$(P) mapping tables for iso2022_jp_3,")
out.append("// generated byte-exact from the CPython oracle (host python3.14). The key is the GL")
out.append("// byte pair (lead<<8 | trail), each byte 0x21..0x7e. Plane 1 also carries 25")
out.append("// combining pairs that decode to a base plus U+309A.")
out.append("")
out.append("package runtime")
out.append("")
out += emit_decode("iso2022JISX0213P1ODecode", p1_dec, "plane 1")
out.append("// iso2022JISX0213P1ODecode2 maps a JIS X 0213 plane 1 GL pair to its two code points")
out.append("// (a base plus the combining mark U+309A), %d entries." % len(p1_dec2))
out.append("var iso2022JISX0213P1ODecode2 = map[uint16][2]rune{")
for (lead, trail) in sorted(p1_dec2):
    a, c = p1_dec2[(lead, trail)]
    out.append("\t0x%04X: {0x%04X, 0x%04X}," % ((lead << 8) | trail, a, c))
out.append("}")
out.append("")
out += emit_encode("iso2022JISX0213P1OEncode", p1_enc, "plane 1")
out.append("// iso2022JISX0213P1OEncode2 maps a base plus combining mark to its JIS X 0213 plane 1")
out.append("// GL pair, %d entries." % len(p1_enc2))
out.append("var iso2022JISX0213P1OEncode2 = map[[2]rune]uint16{")
for (a, c) in sorted(p1_enc2):
    lead, trail = p1_enc2[(a, c)]
    out.append("\t{0x%04X, 0x%04X}: 0x%04X," % (a, c, (lead << 8) | trail))
out.append("}")
out.append("")
out.append("// iso2022JISX0213P1OBase is the set of code points that can begin a plane 1 combining")
out.append("// pair, %d entries." % len(base))
out.append("var iso2022JISX0213P1OBase = map[rune]bool{")
for a in base:
    out.append("\t0x%04X: true," % a)
out.append("}")
out.append("")
out += emit_decode("iso2022JISX0213P2Decode", p2_dec, "plane 2")
out += emit_encode("iso2022JISX0213P2Encode", p2_enc, "plane 2")

open("pkg/runtime/codecs_iso2022_jp3_tables.go", "w").write("\n".join(out))
print("iso2022_jp_3 tables: p1 %d/%d (+%d comb), p2 %d/%d, base %d" % (
    len(p1_dec), len(p1_enc), len(p1_dec2), len(p2_dec), len(p2_enc), len(base)))
