#!/usr/bin/env python3.14
# Authors titlecase_tables.go: the full Unicode titlecase map behind str.title and
# str.capitalize in pkg/objects/strmethods.go.
#
# The map is captured straight from the pinned python3.14's own str.title (the
# conformance oracle), never hand-written, so it titlecases character for
# character the way CPython does. str.title applies the full (multi-character)
# SpecialCasing titlecase mappings CPython bundles, so the German sharp s
# titlecases to Ss and the ligatures to their letters, none of which Go's
# unicode.ToTitle (a 1:1 mapping on an older UCD) reproduces, which is why the
# table is pinned from the interpreter. Rerun to regenerate in place:
#
#     python3.14 pkg/runtime/gen_titlecase_tables.py
#
# str.title uses this map for the first cased character of each word and the full
# lowercase map (with the Final_Sigma context) for the rest; str.capitalize uses
# it for the first character and lowercases the rest. The titlecase of a character
# takes no context of its own, so a per-code-point table is exact. A code point is
# stored only when its titlecase actually changes it, so a lookup miss titlecases
# to the character itself (which is why a lone surrogate, with no mapping, is left
# untouched).
import os
import subprocess

MAX = 0x110000

title = {}
for c in range(MAX):
    ch = chr(c)
    t = ch.title()
    if t != ch:
        title[c] = [ord(x) for x in t]

out = []
out.append("// Code generated by gen_titlecase_tables.py from the pinned CPython 3.14.6\n")
out.append("// str.title. DO NOT EDIT.\n//\n")
out.append("// ucdTitleFull is the full titlecase map (including the multi-character\n")
out.append("// SpecialCasing expansions, like the German sharp s to Ss) str.title applies to\n")
out.append("// the first cased character of each word: a code point maps to the sequence it\n")
out.append("// titlecases to, and a point absent here titlecases to itself. Captured from the\n")
out.append("// interpreter so it agrees with CPython character for character.\n\n")
out.append("package runtime\n\n")
out.append("var ucdTitleFull = map[rune][]rune{\n")
for c in sorted(title):
    lit = "{" + ", ".join("0x%X" % r for r in title[c]) + "}"
    out.append("\t0x%X: %s,\n" % (c, lit))
out.append("}\n")

dst = os.path.join(os.path.dirname(__file__), "titlecase_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

subprocess.run(["gofmt", "-w", dst], check=True)
print("wrote %s: title=%d" % (dst, len(title)))
