#!/usr/bin/env python3.14
# Authors lowercase_tables.go: the full Unicode lowercase map plus the Cased and
# Case_Ignorable sets that back str.lower, str.title and str.swapcase in
# pkg/objects/strmethods.go.
#
# Everything is captured straight from the pinned python3.14's own str.lower (the
# conformance oracle), never hand-written, so it lowercases character for
# character the way CPython does. str.lower applies the full (multi-character)
# SpecialCasing mappings CPython bundles (the Turkish dotted capital I expands to
# i plus a combining dot), none of which Go's unicode.ToLower (a 1:1 mapping on an
# older UCD) reproduces, which is why the table is pinned from the interpreter.
# Rerun to regenerate in place:
#
#     python3.14 pkg/runtime/gen_lowercase_tables.py
#
# The one context rule str.lower applies is Final_Sigma: the Greek capital sigma
# lowercases to the final form when it ends a word (preceded by a cased letter,
# not followed by one, skipping case-ignorable characters between), otherwise to
# the plain form. CPython decides this with its Cased and Case_Ignorable
# properties, so U+03A3 is left out of the per-character map and handled by the
# context walk in pkg/objects/strmethods.go against the two sets below.
#
# The Cased and Case_Ignorable sets are recovered from CPython's own casing
# without reading any UCD file, and the same two sets serve str.title and
# str.swapcase. Cased is the true property: a character X is cased when it makes a
# following letter titlecase-lower, that is (X + "A").title() ends in the lowered
# "a" because X set title's previous_is_cased. Case_Ignorable is recovered from
# handle_capital_sigma, which skips it: X is case-ignorable when ("A" + X +
# "S").lower() still ends in the final sigma while (X + "S") does not, so X is
# transparent between the cased A and the sigma. The sigma walk only ever checks
# casedness on the first non-ignorable character, where the true Cased property
# and the narrower sigma-only notion agree, so one Cased set is exact for both.
# Fuzzing the reconstructed walk against str.lower, str.title and str.capitalize
# over hundreds of thousands of random strings shows zero differences.
import os
import subprocess

MAX = 0x110000
SIGMA = 0x3A3


def is_surrogate(c):
    return 0xD800 <= c <= 0xDFFF


lower = {}
cased = set()
ignorable = set()
for c in range(MAX):
    if is_surrogate(c):
        continue
    ch = chr(c)
    lo = ch.lower()
    if lo != ch and c != SIGMA:
        lower[c] = [ord(x) for x in lo]
    if (ch + "A").title().endswith("a"):
        cased.add(c)
    if ("A" + ch + "Σ").lower().endswith("ς") and not (ch + "Σ").lower().endswith("ς"):
        ignorable.add(c)


def ranges(points):
    out = []
    for c in sorted(points):
        if out and c == out[-1][1] + 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


out = []
out.append("// Code generated by gen_lowercase_tables.py from the pinned CPython 3.14.6\n")
out.append("// str.lower. DO NOT EDIT.\n//\n")
out.append("// ucdLowerFull is the full lowercase map (including the multi-character\n")
out.append("// SpecialCasing expansions, like the Turkish dotted capital I to i plus a\n")
out.append("// combining dot) str.lower applies: a code point maps to the sequence it\n")
out.append("// lowercases to, and a point absent here lowercases to itself. The Greek capital\n")
out.append("// sigma is deliberately absent: its final versus plain form is decided by the\n")
out.append("// Final_Sigma context walk in pkg/objects/strmethods.go. ucdCased and\n")
out.append("// ucdCaseIgnorable are the sorted, inclusive code point ranges that walk\n")
out.append("// consults, recovered from str.lower itself so they agree with CPython.\n\n")
out.append("package runtime\n\n")

out.append("var ucdLowerFull = map[rune][]rune{\n")
for c in sorted(lower):
    lit = "{" + ", ".join("0x%X" % r for r in lower[c]) + "}"
    out.append("\t0x%X: %s,\n" % (c, lit))
out.append("}\n\n")


def emit_ranges(name, points):
    out.append("var %s = [][2]rune{\n" % name)
    for lo, hi in ranges(points):
        out.append("\t{0x%X, 0x%X},\n" % (lo, hi))
    out.append("}\n\n")


emit_ranges("ucdCased", cased)
emit_ranges("ucdCaseIgnorable", ignorable)

dst = os.path.join(os.path.dirname(__file__), "lowercase_tables.go")
with open(dst, "w") as f:
    f.write("".join(out))

subprocess.run(["gofmt", "-w", dst], check=True)
print("wrote %s: lower=%d cased=%d ignorable=%d" % (dst, len(lower), len(cased), len(ignorable)))
