package runtime

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/tamnd/unagi/pkg/objects"
)

// unicodedata is a built-in module. CPython implements it as a C extension over
// the bundled Unicode Character Database; the runtime provides the same surface
// in Go under the import name so `import unicodedata` (and the modules that
// import it, pdb through _pyrepl.utils and doctest through pdb, and stringprep
// through the ucd_3_2_0 accessor below) load.
//
// The general category is computed for real from Go's `unicode` package, which
// tracks the same property, so category() agrees with CPython character for
// character. The canonical combining class, the raw decomposition strings, the
// decomposition and composition mappings that back normalize / is_normalized,
// the decimal/digit/numeric values, the Bidi_Mirrored flag, and the Bidi_Class
// ranges are pinned from the CPython 3.14.6 UCD in unicodedata_tables.go
// (generated by gen_unicodedata_tables.py), so those agree with CPython character
// for character too. The one remaining UCD property Go's standard library does
// not carry and this does not bundle is the name database, so name and lookup
// carry the best-effort behavior documented on each. unidata_version reports the
// UCD version Go's `unicode` package actually ships rather than claiming
// CPython's, so a caller that inspects the category path is not misled.

func init() {
	moduleTable["unicodedata"] = &moduleEntry{builtin: true, exec: initUnicodedata}
}

func initUnicodedata(m *objects.Module) error {
	names := []string{
		"category", "combining", "east_asian_width", "bidirectional",
		"mirrored", "decomposition", "decimal", "digit", "numeric",
		"name", "lookup", "normalize", "is_normalized",
	}
	vals := []objects.Object{
		objects.NewFunc("category", 1, udCategory),
		objects.NewFunc("combining", 1, udCombining),
		objects.NewFunc("east_asian_width", 1, udEastAsianWidth),
		objects.NewFunc("bidirectional", 1, udBidirectional),
		objects.NewFunc("mirrored", 1, udMirrored),
		objects.NewFunc("decomposition", 1, udDecomposition),
		objects.NewFuncKw("decimal", udDecimal),
		objects.NewFuncKw("digit", udDigit),
		objects.NewFuncKw("numeric", udNumeric),
		objects.NewFuncKw("name", udName),
		objects.NewFunc("lookup", 1, udLookup),
		objects.NewFunc("normalize", 2, udNormalize),
		objects.NewFunc("is_normalized", 2, udIsNormalized),
	}
	for i, name := range names {
		if err := objects.StoreAttr(m, name, vals[i]); err != nil {
			return err
		}
	}
	if err := objects.StoreAttr(m, "unidata_version", objects.NewStr(unicode.Version)); err != nil {
		return err
	}

	// ucd_3_2_0 is CPython's accessor for the UCD frozen at Unicode 3.2.0, the
	// version RFC 3454 (stringprep) is written against; stringprep.py binds it as
	// its `unicodedata` and asserts `unidata_version == '3.2.0'` at import. It is
	// modeled here as a namespace over the same function set as the module (a
	// SimpleNamespace calls a stored function unbound, so `ucd_3_2_0.category(c)`
	// has the same one-argument shape), so the category-driven stringprep tables
	// answer correctly and the properties Go's stdlib does not carry keep the same
	// documented best-effort behavior as the module. Its unidata_version reports
	// '3.2.0', matching CPython byte for byte, since that is the identity of this
	// accessor rather than a claim about the data behind it.
	nsNames := append(append([]string{}, names...), "unidata_version")
	nsVals := append(append([]objects.Object{}, vals...), objects.NewStr("3.2.0"))
	ucd320 := objects.NewSimpleNamespace(nsNames, nsVals)
	return objects.StoreAttr(m, "ucd_3_2_0", ucd320)
}

// oneRune pulls the single code point an argument must be, matching the C
// module's "need a single Unicode character" TypeError.
func oneRune(fn string, o objects.Object) (rune, error) {
	s, ok := objects.AsStr(o)
	if !ok {
		return 0, objects.Raise(objects.TypeError,
			"%s() argument 1 must be a unicode character, not %s", fn, o.TypeName())
	}
	runes := []rune(s)
	if len(runes) != 1 {
		return 0, objects.Raise(objects.TypeError,
			"%s() argument 1 must be a unicode character, not str", fn)
	}
	return runes[0], nil
}

// pyCategories lists the 29 Unicode general categories in a fixed order. Go's
// unicode.Categories map also carries an "LC" cased-letter supergroup that is
// not a Python general category, so an explicit list is used rather than
// ranging the map, which would let a cased letter match "LC" first.
var pyCategories = []string{
	"Lu", "Ll", "Lt", "Lm", "Lo",
	"Mn", "Mc", "Me",
	"Nd", "Nl", "No",
	"Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po",
	"Sm", "Sc", "Sk", "So",
	"Zs", "Zl", "Zp",
	"Cc", "Cf", "Cs", "Co",
}

// runeCategory returns the CPython general category code, "Cn" for an
// unassigned code point, computed from Go's unicode tables.
func runeCategory(r rune) string {
	for _, code := range pyCategories {
		if tab := unicode.Categories[code]; tab != nil && unicode.Is(tab, r) {
			return code
		}
	}
	return "Cn"
}

// udCategory is unicodedata.category(chr), computed for real.
func udCategory(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("category", args[0])
	if err != nil {
		return nil, err
	}
	return objects.NewStr(runeCategory(r)), nil
}

// udCombining is unicodedata.combining(chr), the canonical combining class,
// read from the pinned UCD table. A character with no entry has class 0, its
// true value.
func udCombining(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("combining", args[0])
	if err != nil {
		return nil, err
	}
	return objects.NewInt(int64(ucdCombiningClass[r])), nil
}

// wideRanges are the East Asian Wide and Fullwidth blocks. Go carries no
// East_Asian_Width property, so east_asian_width answers from the common wide
// blocks (CJK, Hangul, kana, fullwidth forms, emoji) and returns "N" elsewhere.
// This is a heuristic over the dominant cases, not the full UCD width property.
var wideRanges = []struct{ lo, hi rune }{
	{0x1100, 0x115F},   // Hangul Jamo
	{0x2E80, 0x303E},   // CJK radicals, Kangxi, CJK symbols
	{0x3041, 0x33FF},   // kana, CJK compatibility
	{0x3400, 0x4DBF},   // CJK ext A
	{0x4E00, 0x9FFF},   // CJK unified
	{0xA000, 0xA4CF},   // Yi
	{0xAC00, 0xD7A3},   // Hangul syllables
	{0xF900, 0xFAFF},   // CJK compatibility ideographs
	{0xFE30, 0xFE4F},   // CJK compatibility forms
	{0x1F300, 0x1FAFF}, // emoji and symbols
	{0x20000, 0x3FFFD}, // CJK ext B and beyond
}

// fullwidthRanges are the Fullwidth ("F") forms.
var fullwidthRanges = []struct{ lo, hi rune }{
	{0xFF00, 0xFF60},
	{0xFFE0, 0xFFE6},
}

func inRanges(r rune, rs []struct{ lo, hi rune }) bool {
	for _, x := range rs {
		if r >= x.lo && r <= x.hi {
			return true
		}
	}
	return false
}

// udEastAsianWidth is unicodedata.east_asian_width(chr), a wide-block heuristic.
func udEastAsianWidth(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("east_asian_width", args[0])
	if err != nil {
		return nil, err
	}
	switch {
	case inRanges(r, fullwidthRanges):
		return objects.NewStr("F"), nil
	case inRanges(r, wideRanges):
		return objects.NewStr("W"), nil
	case r >= 0x20 && r <= 0x7E:
		// Printable ASCII is Narrow, the width traceback and _pyrepl assume for
		// Latin text; a control point and everything outside the wide blocks
		// falls to Neutral.
		return objects.NewStr("Na"), nil
	default:
		return objects.NewStr("N"), nil
	}
}

// bidiRange is one [lo, hi] run of code points that share a Bidi_Class, the shape
// ucdBidiRanges in unicodedata_tables.go is generated as. The ranges are sorted
// by lo and do not overlap, so a code point's class is found by binary search.
type bidiRange struct {
	lo, hi rune
	class  string
}

// lookupBidi returns the Bidi_Class of r from the pinned range table, or "" when
// r falls in no stored range (a code point CPython reports no bidi class for).
func lookupBidi(r rune) string {
	lo, hi := 0, len(ucdBidiRanges)
	for lo < hi {
		mid := (lo + hi) / 2
		br := ucdBidiRanges[mid]
		switch {
		case r < br.lo:
			hi = mid
		case r > br.hi:
			lo = mid + 1
		default:
			return br.class
		}
	}
	return ""
}

// udBidirectional is unicodedata.bidirectional(chr), the Bidi_Class read from the
// pinned range table (L, R, AL, EN, NSM, WS and the rest), so stringprep's bidi
// checks and any other caller see the real property. A code point with no bidi
// class answers "", as CPython does.
func udBidirectional(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("bidirectional", args[0])
	if err != nil {
		return nil, err
	}
	return objects.NewStr(lookupBidi(r)), nil
}

// udMirrored is unicodedata.mirrored(chr), the Bidi_Mirrored property read from
// the pinned table: 1 for a mirrored character (the brackets, angle quotes and
// math relations that flip under a right-to-left run) and 0 otherwise.
func udMirrored(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("mirrored", args[0])
	if err != nil {
		return nil, err
	}
	if ucdMirrored[r] {
		return objects.NewInt(1), nil
	}
	return objects.NewInt(0), nil
}

// udDecomposition is unicodedata.decomposition(chr). It returns the raw
// one-level decomposition string (with its <tag>, if any) exactly as CPython
// does, from the pinned table; a Hangul syllable is formatted arithmetically as
// its "L V" or "L V T" jamo, and a character with no decomposition answers "".
func udDecomposition(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("decomposition", args[0])
	if err != nil {
		return nil, err
	}
	if r >= sBase && r < sBase+sCount {
		jamo := hangulDecompose(r)
		parts := make([]string, len(jamo))
		for i, j := range jamo {
			parts[i] = fmt.Sprintf("%04X", j)
		}
		return objects.NewStr(strings.Join(parts, " ")), nil
	}
	return objects.NewStr(ucdDecomposition[r]), nil
}

// numericArg pulls (chr, hasDefault, default) from a decimal/digit/numeric/name
// style call, which is func(chr[, default]).
func numericArg(fn string, pos []objects.Object, kwNames []string) (rune, bool, objects.Object, error) {
	if len(kwNames) > 0 {
		return 0, false, nil, objects.Raise(objects.TypeError, "%s() takes no keyword arguments", fn)
	}
	if len(pos) < 1 || len(pos) > 2 {
		return 0, false, nil, objects.Raise(objects.TypeError,
			"%s() takes one or two arguments", fn)
	}
	r, err := oneRune(fn, pos[0])
	if err != nil {
		return 0, false, nil, err
	}
	if len(pos) == 2 {
		return r, true, pos[1], nil
	}
	return r, false, nil, nil
}

// udDecimal is unicodedata.decimal(chr[, default]), the Decimal value read from
// the pinned table: the ASCII digits, the Arabic-Indic and Devanagari digits,
// the fullwidth digits and every other character carrying a decimal value answer
// it, and anything else falls to the default or the ValueError CPython raises
// when a character has no decimal value and no default is given.
func udDecimal(pos []objects.Object, kwNames []string, _ []objects.Object) (objects.Object, error) {
	r, hasDef, def, err := numericArg("decimal", pos, kwNames)
	if err != nil {
		return nil, err
	}
	if v, ok := ucdDecimal[r]; ok {
		return objects.NewInt(int64(v)), nil
	}
	if hasDef {
		return def, nil
	}
	return nil, objects.Raise(objects.ValueError, "not a decimal")
}

// udDigit is unicodedata.digit(chr[, default]), the Digit value from the pinned
// table. It is a superset of decimal: the superscript and circled digits carry a
// digit value but no decimal value.
func udDigit(pos []objects.Object, kwNames []string, _ []objects.Object) (objects.Object, error) {
	r, hasDef, def, err := numericArg("digit", pos, kwNames)
	if err != nil {
		return nil, err
	}
	if v, ok := ucdDigit[r]; ok {
		return objects.NewInt(int64(v)), nil
	}
	if hasDef {
		return def, nil
	}
	return nil, objects.Raise(objects.ValueError, "not a digit")
}

// udNumeric is unicodedata.numeric(chr[, default]), the Numeric value from the
// pinned table, returned as a float. It is the widest of the three: the
// fractions (½ is 0.5), the CJK numerals and the Roman numerals carry a numeric
// value with no digit or decimal value. A character with none falls to the
// default or the ValueError CPython raises.
func udNumeric(pos []objects.Object, kwNames []string, _ []objects.Object) (objects.Object, error) {
	r, hasDef, def, err := numericArg("numeric", pos, kwNames)
	if err != nil {
		return nil, err
	}
	if v, ok := ucdNumeric[r]; ok {
		return objects.NewFloat(v), nil
	}
	if hasDef {
		return def, nil
	}
	return nil, objects.Raise(objects.ValueError, "not a numeric character")
}

// udName is unicodedata.name(chr[, default]). The name database is UCD data Go
// does not carry, so this returns the default when one is given and otherwise
// raises the ValueError CPython raises for a character with no name.
func udName(pos []objects.Object, kwNames []string, _ []objects.Object) (objects.Object, error) {
	_, hasDef, def, err := numericArg("name", pos, kwNames)
	if err != nil {
		return nil, err
	}
	if hasDef {
		return def, nil
	}
	return nil, objects.Raise(objects.ValueError, "no such name")
}

// udLookup is unicodedata.lookup(name). Without the name database it cannot
// resolve a character, so it raises the KeyError CPython raises for an
// unknown name.
func udLookup(args []objects.Object) (objects.Object, error) {
	name, ok := objects.AsStr(args[0])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "lookup() argument must be str")
	}
	return nil, objects.Raise(objects.KeyError, "undefined character name '%s'", name)
}

// normForms are the four normalization forms normalize accepts.
var normForms = map[string]bool{"NFC": true, "NFD": true, "NFKC": true, "NFKD": true}

// Hangul is decomposed and composed by the arithmetic in UAX #15 rather than
// from a table, so the syllable block need not be enumerated. These are the
// constants that block: L/V/T jamo bases and counts, N = V*T, S = L*N.
const (
	sBase, lBase, vBase, tBase = 0xAC00, 0x1100, 0x1161, 0x11A7
	lCount, vCount, tCount     = 19, 21, 28
	nCount                     = vCount * tCount
	sCount                     = lCount * nCount
)

// ucdCCC is the canonical combining class of r, 0 when it carries no entry.
func ucdCCC(r rune) uint8 { return ucdCombiningClass[r] }

// hangulDecompose returns the L, V (and T, when present) jamo of a Hangul
// syllable, per the UAX #15 arithmetic decomposition.
func hangulDecompose(s rune) []rune {
	i := s - sBase
	l := lBase + i/nCount
	v := vBase + (i%nCount)/tCount
	t := tBase + i%tCount
	if t != tBase {
		return []rune{l, v, t}
	}
	return []rune{l, v}
}

// fullDecompose returns the full decomposition of a single character: the
// arithmetic jamo for a Hangul syllable, the pinned (already fully recursive)
// mapping for a decomposable character, or the character itself otherwise. The
// compat flag selects the compatibility (NFKD/NFKC) mapping over the canonical.
func fullDecompose(r rune, compat bool) []rune {
	if r >= sBase && r < sBase+sCount {
		return hangulDecompose(r)
	}
	if compat {
		if d, ok := ucdCompatDecomp[r]; ok {
			return d
		}
	}
	if d, ok := ucdCanonDecomp[r]; ok {
		return d
	}
	return []rune{r}
}

// canonicalOrder puts a rune slice into canonical order in place: within each
// run of non-starters (combining class > 0) it stably sorts by combining class,
// which is the Canonical Ordering Algorithm of UAX #15. Starters (class 0) are
// fixed points and never move.
func canonicalOrder(buf []rune) {
	for i := 1; i < len(buf); i++ {
		for j := i; j > 0; j-- {
			cj := ucdCCC(buf[j])
			if cj == 0 || ucdCCC(buf[j-1]) <= cj {
				break
			}
			buf[j-1], buf[j] = buf[j], buf[j-1]
		}
	}
}

// decompose returns the fully decomposed, canonically ordered runes of s, the
// NFD (compat false) or NFKD (compat true) form.
func decompose(s string, compat bool) []rune {
	var buf []rune
	for _, r := range s {
		buf = append(buf, fullDecompose(r, compat)...)
	}
	canonicalOrder(buf)
	return buf
}

// hangulCompose recombines an L+V or LV+T jamo pair arithmetically, per UAX #15.
func hangulCompose(a, b rune) (rune, bool) {
	if a >= lBase && a < lBase+lCount && b >= vBase && b < vBase+vCount {
		return sBase + ((a-lBase)*vCount+(b-vBase))*tCount, true
	}
	if a >= sBase && a < sBase+sCount && (a-sBase)%tCount == 0 && b > tBase && b < tBase+tCount {
		return a + (b - tBase), true
	}
	return 0, false
}

// composePair returns the canonical composition of a starter a with a following
// character b, honoring Hangul arithmetic first and then the pinned pair table.
func composePair(a, b rune) (rune, bool) {
	if r, ok := hangulCompose(a, b); ok {
		return r, true
	}
	r, ok := ucdComposePair[[2]rune{a, b}]
	return r, ok
}

// compose runs the Canonical Composition Algorithm of UAX #15 over an already
// decomposed, canonically ordered rune slice, folding each combinable
// non-blocked character back into its starter. It is the NFC/NFKC finishing
// step after decompose.
func compose(buf []rune) []rune {
	if len(buf) == 0 {
		return buf
	}
	out := make([]rune, 0, len(buf))
	out = append(out, buf[0])
	starterIdx := 0
	if ucdCCC(buf[0]) != 0 {
		starterIdx = -1
	}
	prevCC := ucdCCC(buf[0])
	for i := 1; i < len(buf); i++ {
		r := buf[i]
		c := ucdCCC(r)
		// r may compose with the current starter only when it is not blocked:
		// it sits right after the starter (prevCC == 0) or every intervening
		// combining mark has a strictly smaller class.
		if starterIdx >= 0 && (prevCC == 0 || prevCC < c) {
			if comp, ok := composePair(out[starterIdx], r); ok {
				out[starterIdx] = comp
				continue
			}
		}
		out = append(out, r)
		if c == 0 {
			starterIdx = len(out) - 1
		}
		prevCC = c
	}
	return out
}

// normalizeForm applies one of the four forms to s using the pinned tables.
func normalizeForm(form, s string) string {
	compat := form == "NFKD" || form == "NFKC"
	d := decompose(s, compat)
	if form == "NFC" || form == "NFKC" {
		d = compose(d)
	}
	return string(d)
}

// udNormalize is unicodedata.normalize(form, unistr), implemented from the
// pinned decomposition and composition tables per UAX #15.
func udNormalize(args []objects.Object) (objects.Object, error) {
	form, ok := objects.AsStr(args[0])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "normalize() argument 1 must be str")
	}
	s, ok := objects.AsStr(args[1])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "normalize() argument 2 must be str")
	}
	if !normForms[form] {
		return nil, objects.Raise(objects.ValueError, "invalid normalization form")
	}
	return objects.NewStr(normalizeForm(form, s)), nil
}

// udIsNormalized is unicodedata.is_normalized(form, unistr): whether s is
// already in the given form, answered by normalizing and comparing.
func udIsNormalized(args []objects.Object) (objects.Object, error) {
	form, ok := objects.AsStr(args[0])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "is_normalized() argument 1 must be str")
	}
	s, ok := objects.AsStr(args[1])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "is_normalized() argument 2 must be str")
	}
	if !normForms[form] {
		return nil, objects.Raise(objects.ValueError, "invalid normalization form")
	}
	return objects.NewBool(normalizeForm(form, s) == s), nil
}
