package runtime

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"sync"

	"github.com/tamnd/unagi/pkg/frontend"
	"github.com/tamnd/unagi/pkg/objects"
)

// unicodedata is a built-in module. CPython implements it as a C extension over
// the bundled Unicode Character Database; the runtime provides the same surface
// in Go under the import name so `import unicodedata` (and the modules that
// import it, pdb through _pyrepl.utils and doctest through pdb, and stringprep
// through the ucd_3_2_0 accessor below) load.
//
// The general category, the canonical combining class, the raw decomposition
// strings, the decomposition and composition mappings that back normalize /
// is_normalized, the decimal/digit/numeric values, the Bidi_Mirrored flag, and
// the Bidi_Class ranges are all pinned from the CPython 3.14.6 UCD in
// unicodedata_tables.go (generated by gen_unicodedata_tables.py), so they agree
// with CPython character for character. unidata_version reports that same UCD
// version, so category and the reported version name the same data. The character
// name database is pinned too: name() reads the explicit names and formats the
// algorithmic Hangul and CJK-style ranges, and lookup() reverses those and also
// resolves the name aliases and named sequences, so the whole module answers from
// the one UCD.

func init() {
	moduleTable["unicodedata"] = &moduleEntry{builtin: true, exec: initUnicodedata}
	// Fill the namereplace error handler's name lookup with the pinned name
	// database, the way CPython's namereplace reaches unicodedata's getname.
	objects.NameReplaceNameLookup = charName
	// Fill str.casefold's fold map with the pinned CaseFolding.txt C+F table, so
	// the folding agrees with CPython character for character.
	objects.CaseFoldHook = caseFoldLookup
	// Fill str.upper's full uppercase map with the pinned table, so the German
	// sharp s and the ligatures expand the way CPython's str.upper does.
	objects.UpperFullHook = upperFullLookup
	// Fill str.lower's full lowercase map and the Cased/Case_Ignorable sets its
	// Final_Sigma walk consults, so the Greek capital sigma lowercases to its
	// final form word-finally the way CPython's str.lower does.
	objects.LowerFullHook = lowerFullLookup
	objects.CasedHook = casedLookup
	objects.CaseIgnorableHook = caseIgnorableLookup
	// Fill str.title and str.capitalize's full titlecase map with the pinned
	// table, so the German sharp s titlecases to Ss and the ligatures expand the
	// way CPython does.
	objects.TitleFullHook = titleFullLookup
	// Fill str.swapcase's branch predicates with the pinned Uppercase/Lowercase
	// sets, so it lowercases the uppercase characters and uppercases the lowercase
	// ones while leaving the titlecase and caseless ones the way CPython does.
	objects.UppercaseHook = uppercaseLookup
	objects.LowercaseHook = lowercaseLookup
	// Fill str.isalpha / isalnum / isdecimal / isdigit / isnumeric / isprintable's
	// classification with the pinned category and digit/numeric value tables, so
	// they answer for the newer blocks the way CPython does.
	objects.CategoryHook = runeCategory
	objects.DigitHook = func(r rune) bool { _, ok := ucdDigit[r]; return ok }
	objects.NumericHook = func(r rune) bool { _, ok := ucdNumeric[r]; return ok }
	// Fill str.isidentifier's classification with the pinned XID_Start/XID_Continue
	// sets, so an identifier made of the newer blocks is recognized the way CPython
	// does.
	objects.IDStartHook = func(r rune) bool { return inRuneRanges(ucdXidStart, r) }
	objects.IDContinueHook = func(r rune) bool { return inRuneRanges(ucdXidContinue, r) }
	// Resolve the frontend lexer's \N{NAME} string escape through the same pinned
	// name database lookup() uses, so a \N escape in a source literal names the
	// same character unicodedata.lookup would.
	frontend.NamedUnicodeLookup = func(name string) (string, bool) {
		nameOnce.Do(buildNameIndex)
		return charLookup(name)
	}
}

// caseFoldLookup returns the full case fold of a code point, or nil when the
// point folds to itself (absent from the pinned table).
func caseFoldLookup(r rune) []rune {
	return ucdCaseFold[r]
}

// upperFullLookup returns the full uppercase of a code point, or nil when the
// point uppercases to itself (absent from the pinned table).
func upperFullLookup(r rune) []rune {
	return ucdUpperFull[r]
}

// lowerFullLookup returns the full lowercase of a code point, or nil when the
// point lowercases to itself (absent from the pinned table). The Greek capital
// sigma is absent by design; its final form is chosen by the Final_Sigma walk.
func lowerFullLookup(r rune) []rune {
	return ucdLowerFull[r]
}

// titleFullLookup returns the full titlecase of a code point, or nil when the
// point titlecases to itself (absent from the pinned table).
func titleFullLookup(r rune) []rune {
	return ucdTitleFull[r]
}

// casedLookup reports whether a code point is Cased, the property str.lower's
// Final_Sigma walk consults for the letters bounding the sigma and str.title uses
// to find the first cased character of each word.
func casedLookup(r rune) bool {
	return inRuneRanges(ucdCased, r)
}

// caseIgnorableLookup reports whether a code point is Case_Ignorable, the
// characters str.lower's Final_Sigma walk skips over between cased letters.
func caseIgnorableLookup(r rune) bool {
	return inRuneRanges(ucdCaseIgnorable, r)
}

// uppercaseLookup reports whether a code point has the Uppercase property, so
// str.swapcase lowercases it.
func uppercaseLookup(r rune) bool {
	return inRuneRanges(ucdUppercase, r)
}

// lowercaseLookup reports whether a code point has the Lowercase property, so
// str.swapcase uppercases it.
func lowercaseLookup(r rune) bool {
	return inRuneRanges(ucdLowercase, r)
}

// inRuneRanges reports whether r falls in one of the sorted, inclusive ranges by
// binary search.
func inRuneRanges(ranges [][2]rune, r rune) bool {
	lo, hi := 0, len(ranges)
	for lo < hi {
		mid := (lo + hi) / 2
		switch {
		case r < ranges[mid][0]:
			hi = mid
		case r > ranges[mid][1]:
			lo = mid + 1
		default:
			return true
		}
	}
	return false
}

func initUnicodedata(m *objects.Module) error {
	names := []string{
		"category", "combining", "east_asian_width", "bidirectional",
		"mirrored", "decomposition", "decimal", "digit", "numeric",
		"name", "lookup", "normalize", "is_normalized",
	}
	vals := []objects.Object{
		objects.NewFunc("category", 1, udCategory),
		objects.NewFunc("combining", 1, udCombining),
		objects.NewFunc("east_asian_width", 1, udEastAsianWidth),
		objects.NewFunc("bidirectional", 1, udBidirectional),
		objects.NewFunc("mirrored", 1, udMirrored),
		objects.NewFunc("decomposition", 1, udDecomposition),
		objects.NewFuncKw("decimal", udDecimal),
		objects.NewFuncKw("digit", udDigit),
		objects.NewFuncKw("numeric", udNumeric),
		objects.NewFuncKw("name", udName),
		objects.NewFunc("lookup", 1, udLookup),
		objects.NewFunc("normalize", 2, udNormalize),
		objects.NewFunc("is_normalized", 2, udIsNormalized),
	}
	for i, name := range names {
		if err := objects.StoreAttr(m, name, vals[i]); err != nil {
			return err
		}
	}
	if err := objects.StoreAttr(m, "unidata_version", objects.NewStr(ucdVersion)); err != nil {
		return err
	}

	// ucd_3_2_0 is CPython's accessor for the UCD frozen at Unicode 3.2.0, the
	// version RFC 3454 (stringprep) is written against; stringprep.py binds it as
	// its `unicodedata` and asserts `unidata_version == '3.2.0'` at import. It is
	// modeled here as a namespace over the same function set as the module (a
	// SimpleNamespace calls a stored function unbound, so `ucd_3_2_0.category(c)`
	// has the same one-argument shape), so the category-driven stringprep tables
	// answer correctly and the properties Go's stdlib does not carry keep the same
	// documented best-effort behavior as the module. Its unidata_version reports
	// '3.2.0', matching CPython byte for byte, since that is the identity of this
	// accessor rather than a claim about the data behind it.
	nsNames := append(append([]string{}, names...), "unidata_version")
	nsVals := append(append([]objects.Object{}, vals...), objects.NewStr("3.2.0"))
	ucd320 := objects.NewSimpleNamespace(nsNames, nsVals)
	return objects.StoreAttr(m, "ucd_3_2_0", ucd320)
}

// oneRune pulls the single code point an argument must be, matching the C
// module's "need a single Unicode character" TypeError.
func oneRune(fn string, o objects.Object) (rune, error) {
	s, ok := objects.AsStr(o)
	if !ok {
		return 0, objects.Raise(objects.TypeError,
			"%s() argument 1 must be a unicode character, not %s", fn, o.TypeName())
	}
	// StrRunes decodes WTF-8 so a lone surrogate stays one code point; []rune
	// would split its three bytes into three U+FFFD runes and wrongly fail the
	// single-character check. CPython accepts any single code point here.
	runes := objects.StrRunes(s)
	if len(runes) != 1 {
		return 0, objects.Raise(objects.TypeError,
			"%s() argument 1 must be a unicode character, not str", fn)
	}
	return runes[0], nil
}

// categoryRange is one [lo, hi] run of code points that share a general
// category, the shape ucdCategoryRanges in unicodedata_tables.go is generated as.
// The ranges are sorted by lo and do not overlap, so a code point's category is
// found by binary search.
type categoryRange struct {
	lo, hi rune
	class  string
}

// runeCategory returns the CPython general category code from the pinned range
// table, "Cn" for a code point in no stored range (an unassigned one).
func runeCategory(r rune) string {
	lo, hi := 0, len(ucdCategoryRanges)
	for lo < hi {
		mid := (lo + hi) / 2
		cr := ucdCategoryRanges[mid]
		switch {
		case r < cr.lo:
			hi = mid
		case r > cr.hi:
			lo = mid + 1
		default:
			return cr.class
		}
	}
	return "Cn"
}

// udCategory is unicodedata.category(chr), read from the pinned UCD so it matches
// CPython 3.14 rather than the older UCD Go's `unicode` package tracks.
func udCategory(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("category", args[0])
	if err != nil {
		return nil, err
	}
	return objects.NewStr(runeCategory(r)), nil
}

// udCombining is unicodedata.combining(chr), the canonical combining class,
// read from the pinned UCD table. A character with no entry has class 0, its
// true value.
func udCombining(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("combining", args[0])
	if err != nil {
		return nil, err
	}
	return objects.NewInt(int64(ucdCombiningClass[r])), nil
}

// eawRange is one [lo, hi] run of code points that share an East_Asian_Width
// class, the shape ucdEastAsianWidthRanges in east_asian_width_tables.go is
// generated as. The ranges are sorted by lo and do not overlap, so a code point's
// width is found by binary search, and the Neutral class is left out as the
// default.
type eawRange struct {
	lo, hi rune
	class  string
}

// runeEastAsianWidth returns the East_Asian_Width class from the pinned range
// table, "N" (Neutral) for a code point in no stored range, matching CPython.
func runeEastAsianWidth(r rune) string {
	lo, hi := 0, len(ucdEastAsianWidthRanges)
	for lo < hi {
		mid := (lo + hi) / 2
		er := ucdEastAsianWidthRanges[mid]
		switch {
		case r < er.lo:
			hi = mid
		case r > er.hi:
			lo = mid + 1
		default:
			return er.class
		}
	}
	return "N"
}

// udEastAsianWidth is unicodedata.east_asian_width(chr), read from the pinned UCD
// so it carries the full six-class property (F, H, W, Na, A, N).
func udEastAsianWidth(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("east_asian_width", args[0])
	if err != nil {
		return nil, err
	}
	return objects.NewStr(runeEastAsianWidth(r)), nil
}

// bidiRange is one [lo, hi] run of code points that share a Bidi_Class, the shape
// ucdBidiRanges in unicodedata_tables.go is generated as. The ranges are sorted
// by lo and do not overlap, so a code point's class is found by binary search.
type bidiRange struct {
	lo, hi rune
	class  string
}

// lookupBidi returns the Bidi_Class of r from the pinned range table, or "" when
// r falls in no stored range (a code point CPython reports no bidi class for).
func lookupBidi(r rune) string {
	lo, hi := 0, len(ucdBidiRanges)
	for lo < hi {
		mid := (lo + hi) / 2
		br := ucdBidiRanges[mid]
		switch {
		case r < br.lo:
			hi = mid
		case r > br.hi:
			lo = mid + 1
		default:
			return br.class
		}
	}
	return ""
}

// udBidirectional is unicodedata.bidirectional(chr), the Bidi_Class read from the
// pinned range table (L, R, AL, EN, NSM, WS and the rest), so stringprep's bidi
// checks and any other caller see the real property. A code point with no bidi
// class answers "", as CPython does.
func udBidirectional(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("bidirectional", args[0])
	if err != nil {
		return nil, err
	}
	return objects.NewStr(lookupBidi(r)), nil
}

// udMirrored is unicodedata.mirrored(chr), the Bidi_Mirrored property read from
// the pinned table: 1 for a mirrored character (the brackets, angle quotes and
// math relations that flip under a right-to-left run) and 0 otherwise.
func udMirrored(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("mirrored", args[0])
	if err != nil {
		return nil, err
	}
	if ucdMirrored[r] {
		return objects.NewInt(1), nil
	}
	return objects.NewInt(0), nil
}

// udDecomposition is unicodedata.decomposition(chr). It returns the raw
// one-level decomposition string (with its <tag>, if any) exactly as CPython
// does, from the pinned table; a Hangul syllable is formatted arithmetically as
// its "L V" or "L V T" jamo, and a character with no decomposition answers "".
func udDecomposition(args []objects.Object) (objects.Object, error) {
	r, err := oneRune("decomposition", args[0])
	if err != nil {
		return nil, err
	}
	if r >= sBase && r < sBase+sCount {
		jamo := hangulDecompose(r)
		parts := make([]string, len(jamo))
		for i, j := range jamo {
			parts[i] = fmt.Sprintf("%04X", j)
		}
		return objects.NewStr(strings.Join(parts, " ")), nil
	}
	return objects.NewStr(ucdDecomposition[r]), nil
}

// numericArg pulls (chr, hasDefault, default) from a decimal/digit/numeric/name
// style call, which is func(chr[, default]).
func numericArg(fn string, pos []objects.Object, kwNames []string) (rune, bool, objects.Object, error) {
	if len(kwNames) > 0 {
		return 0, false, nil, objects.Raise(objects.TypeError, "%s() takes no keyword arguments", fn)
	}
	if len(pos) < 1 || len(pos) > 2 {
		return 0, false, nil, objects.Raise(objects.TypeError,
			"%s() takes one or two arguments", fn)
	}
	r, err := oneRune(fn, pos[0])
	if err != nil {
		return 0, false, nil, err
	}
	if len(pos) == 2 {
		return r, true, pos[1], nil
	}
	return r, false, nil, nil
}

// udDecimal is unicodedata.decimal(chr[, default]), the Decimal value read from
// the pinned table: the ASCII digits, the Arabic-Indic and Devanagari digits,
// the fullwidth digits and every other character carrying a decimal value answer
// it, and anything else falls to the default or the ValueError CPython raises
// when a character has no decimal value and no default is given.
func udDecimal(pos []objects.Object, kwNames []string, _ []objects.Object) (objects.Object, error) {
	r, hasDef, def, err := numericArg("decimal", pos, kwNames)
	if err != nil {
		return nil, err
	}
	if v, ok := ucdDecimal[r]; ok {
		return objects.NewInt(int64(v)), nil
	}
	if hasDef {
		return def, nil
	}
	return nil, objects.Raise(objects.ValueError, "not a decimal")
}

// udDigit is unicodedata.digit(chr[, default]), the Digit value from the pinned
// table. It is a superset of decimal: the superscript and circled digits carry a
// digit value but no decimal value.
func udDigit(pos []objects.Object, kwNames []string, _ []objects.Object) (objects.Object, error) {
	r, hasDef, def, err := numericArg("digit", pos, kwNames)
	if err != nil {
		return nil, err
	}
	if v, ok := ucdDigit[r]; ok {
		return objects.NewInt(int64(v)), nil
	}
	if hasDef {
		return def, nil
	}
	return nil, objects.Raise(objects.ValueError, "not a digit")
}

// udNumeric is unicodedata.numeric(chr[, default]), the Numeric value from the
// pinned table, returned as a float. It is the widest of the three: the
// fractions (½ is 0.5), the CJK numerals and the Roman numerals carry a numeric
// value with no digit or decimal value. A character with none falls to the
// default or the ValueError CPython raises.
func udNumeric(pos []objects.Object, kwNames []string, _ []objects.Object) (objects.Object, error) {
	r, hasDef, def, err := numericArg("numeric", pos, kwNames)
	if err != nil {
		return nil, err
	}
	if v, ok := ucdNumeric[r]; ok {
		return objects.NewFloat(v), nil
	}
	if hasDef {
		return def, nil
	}
	return nil, objects.Raise(objects.ValueError, "not a numeric character")
}

// nameRange is one run of code points whose names are algorithmic, of the form
// "PREFIX-HEX" (the CJK ideograph blocks and a few others), the shape
// ucdNameRanges in unicodedata_tables.go is generated as. The ranges are sorted
// by lo and do not overlap.
type nameRange struct {
	lo, hi rune
	prefix string
}

// The Hangul syllable short-name jamo, the leading (L), vowel (V) and trailing
// (T) components a syllable name is built from ("HANGUL SYLLABLE " + L + V + T).
// These are Unicode standard constants that do not change between UCD versions,
// so they are kept here rather than generated; hangulName and the reverse parse
// in charLookup are checked byte-exact against the oracle across every syllable.
var (
	jamoL = []string{
		"G", "GG", "N", "D", "DD", "R", "M", "B", "BB", "S", "SS",
		"", "J", "JJ", "C", "K", "T", "P", "H",
	}
	jamoV = []string{
		"A", "AE", "YA", "YAE", "EO", "E", "YEO", "YE", "O", "WA", "WAE",
		"OE", "YO", "U", "WEO", "WE", "WI", "YU", "EU", "YI", "I",
	}
	jamoT = []string{
		"", "G", "GG", "GS", "N", "NJ", "NH", "D", "L", "LG", "LM", "LB",
		"LS", "LT", "LP", "LH", "M", "B", "BS", "S", "SS", "NG", "J", "C",
		"K", "T", "P", "H",
	}
)

// hangulName formats the name of a Hangul syllable from its L, V and T jamo, the
// same arithmetic decomposition unicodedata uses.
func hangulName(r rune) string {
	i := r - sBase
	return "HANGUL SYLLABLE " + jamoL[i/nCount] + jamoV[(i%nCount)/tCount] + jamoT[i%tCount]
}

// charName returns the name of r and whether it has one, matching unicodedata's
// name(): a Hangul syllable and the algorithmic "PREFIX-HEX" ranges are
// formatted, everything else is read from the pinned explicit-name table.
func charName(r rune) (string, bool) {
	if r >= sBase && r < sBase+sCount {
		return hangulName(r), true
	}
	lo, hi := 0, len(ucdNameRanges)
	for lo < hi {
		mid := (lo + hi) / 2
		nr := ucdNameRanges[mid]
		switch {
		case r < nr.lo:
			hi = mid
		case r > nr.hi:
			lo = mid + 1
		default:
			return fmt.Sprintf("%s-%04X", nr.prefix, r), true
		}
	}
	if n, ok := ucdNames[r]; ok {
		return n, true
	}
	return "", false
}

// nameOnce guards the reverse name index, built lazily on the first lookup() so
// import does not pay for it. nameToRune reverses the explicit-name table and
// jamoT{L,V}Order list the jamo longest-first for greedy prefix matching.
var (
	nameOnce   sync.Once
	nameToRune map[string]rune
	jamoLOrder []int
	jamoVOrder []int
	tByName    map[string]rune
)

func buildNameIndex() {
	nameToRune = make(map[string]rune, len(ucdNames))
	for r, n := range ucdNames {
		nameToRune[n] = r
	}
	jamoLOrder = make([]int, len(jamoL))
	for i := range jamoL {
		jamoLOrder[i] = i
	}
	sort.SliceStable(jamoLOrder, func(a, b int) bool {
		return len(jamoL[jamoLOrder[a]]) > len(jamoL[jamoLOrder[b]])
	})
	jamoVOrder = make([]int, len(jamoV))
	for i := range jamoV {
		jamoVOrder[i] = i
	}
	sort.SliceStable(jamoVOrder, func(a, b int) bool {
		return len(jamoV[jamoVOrder[a]]) > len(jamoV[jamoVOrder[b]])
	})
	tByName = make(map[string]rune, len(jamoT))
	for i, s := range jamoT {
		tByName[s] = rune(i)
	}
}

// charLookup resolves a character name to its string as unicodedata.lookup does:
// a "HANGUL SYLLABLE ..." or "PREFIX-HEX" algorithmic name, then the reverse of
// the explicit-name table, then the name aliases and named sequences (whose
// result may be more than one character). The bool reports whether it resolved.
func charLookup(name string) (string, bool) {
	if r, ok := lookupHangul(name); ok {
		return string(r), true
	}
	if r, ok := lookupRange(name); ok {
		return string(r), true
	}
	if r, ok := nameToRune[name]; ok {
		return string(r), true
	}
	if s, ok := ucdNameAliases[name]; ok {
		return s, true
	}
	return "", false
}

// lookupHangul parses a "HANGUL SYLLABLE " name back to its syllable by matching
// the L, V and T jamo greedily (longest short-name first), requiring the trailing
// jamo to consume the rest exactly, so only the one syllable that formats to the
// name resolves.
func lookupHangul(name string) (rune, bool) {
	const pfx = "HANGUL SYLLABLE "
	if !strings.HasPrefix(name, pfx) {
		return 0, false
	}
	rest := name[len(pfx):]
	for _, li := range jamoLOrder {
		if !strings.HasPrefix(rest, jamoL[li]) {
			continue
		}
		r1 := rest[len(jamoL[li]):]
		for _, vi := range jamoVOrder {
			if !strings.HasPrefix(r1, jamoV[vi]) {
				continue
			}
			if ti, ok := tByName[r1[len(jamoV[vi]):]]; ok {
				return sBase + (rune(li)*vCount+rune(vi))*tCount + ti, true
			}
		}
	}
	return 0, false
}

// lookupRange parses an algorithmic "PREFIX-HEX" name back to its code point,
// requiring the hex to be the exact "%04X" of a code point inside a range with
// that prefix, so a wrong prefix, out-of-range value or stray leading zero does
// not resolve.
func lookupRange(name string) (rune, bool) {
	i := strings.LastIndexByte(name, '-')
	if i <= 0 {
		return 0, false
	}
	prefix, hexs := name[:i], name[i+1:]
	v, err := strconv.ParseInt(hexs, 16, 32)
	if err != nil {
		return 0, false
	}
	r := rune(v)
	for _, nr := range ucdNameRanges {
		if nr.prefix == prefix && r >= nr.lo && r <= nr.hi && fmt.Sprintf("%04X", r) == hexs {
			return r, true
		}
	}
	return 0, false
}

// udName is unicodedata.name(chr[, default]), the character name from the pinned
// database. A character with no name returns the default when one is given and
// otherwise raises the ValueError CPython raises.
func udName(pos []objects.Object, kwNames []string, _ []objects.Object) (objects.Object, error) {
	r, hasDef, def, err := numericArg("name", pos, kwNames)
	if err != nil {
		return nil, err
	}
	if n, ok := charName(r); ok {
		return objects.NewStr(n), nil
	}
	if hasDef {
		return def, nil
	}
	return nil, objects.Raise(objects.ValueError, "no such name")
}

// udLookup is unicodedata.lookup(name), the character (or named sequence) a name
// resolves to. An unknown name raises the KeyError CPython raises.
func udLookup(args []objects.Object) (objects.Object, error) {
	name, ok := objects.AsStr(args[0])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "lookup() argument must be str")
	}
	nameOnce.Do(buildNameIndex)
	if s, ok := charLookup(name); ok {
		return objects.NewStr(s), nil
	}
	return nil, objects.Raise(objects.KeyError, "undefined character name '%s'", name)
}

// normForms are the four normalization forms normalize accepts.
var normForms = map[string]bool{"NFC": true, "NFD": true, "NFKC": true, "NFKD": true}

// Hangul is decomposed and composed by the arithmetic in UAX #15 rather than
// from a table, so the syllable block need not be enumerated. These are the
// constants that block: L/V/T jamo bases and counts, N = V*T, S = L*N.
const (
	sBase, lBase, vBase, tBase = 0xAC00, 0x1100, 0x1161, 0x11A7
	lCount, vCount, tCount     = 19, 21, 28
	nCount                     = vCount * tCount
	sCount                     = lCount * nCount
)

// ucdCCC is the canonical combining class of r, 0 when it carries no entry.
func ucdCCC(r rune) uint8 { return ucdCombiningClass[r] }

// hangulDecompose returns the L, V (and T, when present) jamo of a Hangul
// syllable, per the UAX #15 arithmetic decomposition.
func hangulDecompose(s rune) []rune {
	i := s - sBase
	l := lBase + i/nCount
	v := vBase + (i%nCount)/tCount
	t := tBase + i%tCount
	if t != tBase {
		return []rune{l, v, t}
	}
	return []rune{l, v}
}

// fullDecompose returns the full decomposition of a single character: the
// arithmetic jamo for a Hangul syllable, the pinned (already fully recursive)
// mapping for a decomposable character, or the character itself otherwise. The
// compat flag selects the compatibility (NFKD/NFKC) mapping over the canonical.
func fullDecompose(r rune, compat bool) []rune {
	if r >= sBase && r < sBase+sCount {
		return hangulDecompose(r)
	}
	if compat {
		if d, ok := ucdCompatDecomp[r]; ok {
			return d
		}
	}
	if d, ok := ucdCanonDecomp[r]; ok {
		return d
	}
	return []rune{r}
}

// canonicalOrder puts a rune slice into canonical order in place: within each
// run of non-starters (combining class > 0) it stably sorts by combining class,
// which is the Canonical Ordering Algorithm of UAX #15. Starters (class 0) are
// fixed points and never move.
func canonicalOrder(buf []rune) {
	for i := 1; i < len(buf); i++ {
		for j := i; j > 0; j-- {
			cj := ucdCCC(buf[j])
			if cj == 0 || ucdCCC(buf[j-1]) <= cj {
				break
			}
			buf[j-1], buf[j] = buf[j], buf[j-1]
		}
	}
}

// decompose returns the fully decomposed, canonically ordered runes of s, the
// NFD (compat false) or NFKD (compat true) form.
func decompose(s string, compat bool) []rune {
	var buf []rune
	for _, r := range s {
		buf = append(buf, fullDecompose(r, compat)...)
	}
	canonicalOrder(buf)
	return buf
}

// hangulCompose recombines an L+V or LV+T jamo pair arithmetically, per UAX #15.
func hangulCompose(a, b rune) (rune, bool) {
	if a >= lBase && a < lBase+lCount && b >= vBase && b < vBase+vCount {
		return sBase + ((a-lBase)*vCount+(b-vBase))*tCount, true
	}
	if a >= sBase && a < sBase+sCount && (a-sBase)%tCount == 0 && b > tBase && b < tBase+tCount {
		return a + (b - tBase), true
	}
	return 0, false
}

// composePair returns the canonical composition of a starter a with a following
// character b, honoring Hangul arithmetic first and then the pinned pair table.
func composePair(a, b rune) (rune, bool) {
	if r, ok := hangulCompose(a, b); ok {
		return r, true
	}
	r, ok := ucdComposePair[[2]rune{a, b}]
	return r, ok
}

// compose runs the Canonical Composition Algorithm of UAX #15 over an already
// decomposed, canonically ordered rune slice, folding each combinable
// non-blocked character back into its starter. It is the NFC/NFKC finishing
// step after decompose.
func compose(buf []rune) []rune {
	if len(buf) == 0 {
		return buf
	}
	out := make([]rune, 0, len(buf))
	out = append(out, buf[0])
	starterIdx := 0
	if ucdCCC(buf[0]) != 0 {
		starterIdx = -1
	}
	prevCC := ucdCCC(buf[0])
	for i := 1; i < len(buf); i++ {
		r := buf[i]
		c := ucdCCC(r)
		// r may compose with the current starter only when it is not blocked:
		// it sits right after the starter (prevCC == 0) or every intervening
		// combining mark has a strictly smaller class.
		if starterIdx >= 0 && (prevCC == 0 || prevCC < c) {
			if comp, ok := composePair(out[starterIdx], r); ok {
				out[starterIdx] = comp
				continue
			}
		}
		out = append(out, r)
		if c == 0 {
			starterIdx = len(out) - 1
		}
		prevCC = c
	}
	return out
}

// normalizeForm applies one of the four forms to s using the pinned tables.
func normalizeForm(form, s string) string {
	compat := form == "NFKD" || form == "NFKC"
	d := decompose(s, compat)
	if form == "NFC" || form == "NFKC" {
		d = compose(d)
	}
	return string(d)
}

// udNormalize is unicodedata.normalize(form, unistr), implemented from the
// pinned decomposition and composition tables per UAX #15.
func udNormalize(args []objects.Object) (objects.Object, error) {
	form, ok := objects.AsStr(args[0])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "normalize() argument 1 must be str")
	}
	s, ok := objects.AsStr(args[1])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "normalize() argument 2 must be str")
	}
	if !normForms[form] {
		return nil, objects.Raise(objects.ValueError, "invalid normalization form")
	}
	return objects.NewStr(normalizeForm(form, s)), nil
}

// udIsNormalized is unicodedata.is_normalized(form, unistr): whether s is
// already in the given form, answered by normalizing and comparing.
func udIsNormalized(args []objects.Object) (objects.Object, error) {
	form, ok := objects.AsStr(args[0])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "is_normalized() argument 1 must be str")
	}
	s, ok := objects.AsStr(args[1])
	if !ok {
		return nil, objects.Raise(objects.TypeError, "is_normalized() argument 2 must be str")
	}
	if !normForms[form] {
		return nil, objects.Raise(objects.ValueError, "invalid normalization form")
	}
	return objects.NewBool(normalizeForm(form, s) == s), nil
}
