// Package emit lowers the frontend AST to Go source. M0 emits boxed-tier code
// only: every value is an objects.Object, every fallible operation runs
// through pkg/objects, and expression trees flatten into checked temporaries.
// The output is deterministic and gofmt-clean; making it pretty is the typed
// tier's job in later milestones.
package emit

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"

	"github.com/tamnd/unagi/pkg/frontend"
)

// Error is a compile-time rejection with a source position, for constructs
// the M0 emitter does not lower.
type Error struct {
	File string
	Pos  frontend.Pos
	Msg  string
}

func (e *Error) Error() string {
	return fmt.Sprintf("%s:%d:%d: error: %s", e.File, e.Pos.Line, e.Pos.Col, e.Msg)
}

// builtins the M0 emitter lowers when the name is not shadowed. The value is
// the argument count contract; -1 means variadic (checked in the call site
// lowering instead).
var builtinNames = map[string]bool{
	"print": true, "len": true, "range": true, "str": true, "repr": true,
	"int": true, "float": true, "bool": true, "abs": true,
}

// Module lowers a parsed module to a complete Go main package. file is the
// source path, used in the generated header and in error messages.
func Module(mod *frontend.Module, file string) ([]byte, error) {
	e := &emitter{file: file, defs: map[string]*frontend.FuncDef{}}

	var body []frontend.Stmt
	var defs []*frontend.FuncDef
	for _, s := range mod.Body {
		if d, ok := s.(*frontend.FuncDef); ok {
			if _, dup := e.defs[d.Name]; dup {
				// Redefinition is legal Python; M0 hoists defs, so the second
				// binding cannot take effect and we refuse it instead.
				return nil, e.errf(d.Span(), "redefining function %q is not supported in M0", d.Name)
			}
			e.defs[d.Name] = d
			defs = append(defs, d)
			continue
		}
		body = append(body, s)
	}

	var progs []byte
	for _, d := range defs {
		src, err := e.emitFunc(d)
		if err != nil {
			return nil, err
		}
		progs = append(progs, src...)
	}
	mainSrc, err := e.emitMain(body)
	if err != nil {
		return nil, err
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by unagi from %s. DO NOT EDIT.\n", file)
	out.WriteString("package main\n\nimport (\n\t\"os\"\n\n")
	if e.usedObjects {
		out.WriteString("\t\"github.com/tamnd/unagi/pkg/objects\"\n")
	}
	out.WriteString("\t\"github.com/tamnd/unagi/pkg/runtime\"\n)\n\n")
	out.WriteString("func main() {\n\tif err := pymain(); err != nil {\n\t\truntime.PrintUncaught(err)\n\t\tos.Exit(1)\n\t}\n}\n\n")
	out.Write(mainSrc)
	out.Write(progs)

	formatted, ferr := format.Source(out.Bytes())
	if ferr != nil {
		// A formatting failure is an emitter bug; surface the raw source so
		// it can be diagnosed from the error alone.
		return nil, fmt.Errorf("emit: generated invalid Go (%v):\n%s", ferr, out.String())
	}
	return formatted, nil
}

type emitter struct {
	file        string
	defs        map[string]*frontend.FuncDef
	usedObjects bool
}

func (e *emitter) errf(pos frontend.Pos, format string, args ...any) error {
	return &Error{File: e.file, Pos: pos, Msg: fmt.Sprintf(format, args...)}
}

// obj marks pkg/objects as imported and returns the qualified name, so the
// import list stays exact even for programs that never touch a value.
func (e *emitter) obj(name string) string {
	e.usedObjects = true
	return "objects." + name
}

func mangle(name string) string { return "u_" + name }

// loopInfo tracks one enclosing Python loop. flag is the broke-out marker
// variable, set only when the loop carries an else block.
type loopInfo struct {
	flag string
}

// fnCtx emits one Go function body: pymain for the module body, or one
// emitted def. Temporaries count per function so output stays deterministic.
type fnCtx struct {
	e      *emitter
	buf    bytes.Buffer
	indent int
	tmp    int
	locals map[string]bool
	inFunc bool
	loops  []*loopInfo
}

func (f *fnCtx) line(s string) {
	for i := 0; i < f.indent; i++ {
		f.buf.WriteByte('\t')
	}
	f.buf.WriteString(s)
	f.buf.WriteByte('\n')
}

func (f *fnCtx) linef(format string, args ...any) {
	f.line(fmt.Sprintf(format, args...))
}

func (f *fnCtx) newTmp() string {
	f.tmp++
	return fmt.Sprintf("t%d", f.tmp)
}

// errRet is the error-path return statement for this function shape.
func (f *fnCtx) errRet() string {
	if f.inFunc {
		return "return nil, err"
	}
	return "return err"
}

// check emits the error check that follows every fallible runtime call.
func (f *fnCtx) check() {
	f.line("if err != nil {")
	f.indent++
	f.line(f.errRet())
	f.indent--
	f.line("}")
}

func (e *emitter) emitMain(body []frontend.Stmt) ([]byte, error) {
	f := &fnCtx{e: e, indent: 1, locals: map[string]bool{}}
	collectAssigned(body, f.locals)
	var head bytes.Buffer
	head.WriteString("func pymain() error {\n")
	for _, name := range sortedNames(f.locals) {
		fmt.Fprintf(&head, "\tvar %s %s\n\t_ = %s\n", mangle(name), e.obj("Object"), mangle(name))
	}
	if err := f.stmts(body); err != nil {
		return nil, err
	}
	f.line("return nil")
	head.Write(f.buf.Bytes())
	head.WriteString("}\n\n")
	return head.Bytes(), nil
}

func (e *emitter) emitFunc(d *frontend.FuncDef) ([]byte, error) {
	f := &fnCtx{e: e, indent: 1, locals: map[string]bool{}, inFunc: true}
	for _, p := range d.Params {
		f.locals[p] = true
	}
	assigned := map[string]bool{}
	collectAssigned(d.Body, assigned)
	var head bytes.Buffer
	fmt.Fprintf(&head, "// %s is Python def %s.\nfunc %s(", mangle(d.Name), d.Name, mangle(d.Name))
	for i, p := range d.Params {
		if i > 0 {
			head.WriteString(", ")
		}
		fmt.Fprintf(&head, "%s %s", mangle(p), e.obj("Object"))
	}
	fmt.Fprintf(&head, ") (%s, error) {\n", e.obj("Object"))
	for _, name := range sortedNames(assigned) {
		if f.locals[name] {
			continue
		}
		f.locals[name] = true
		fmt.Fprintf(&head, "\tvar %s %s\n\t_ = %s\n", mangle(name), e.obj("Object"), mangle(name))
	}
	if err := f.stmts(d.Body); err != nil {
		return nil, err
	}
	f.linef("return %s, nil", e.obj("None"))
	head.Write(f.buf.Bytes())
	head.WriteString("}\n\n")
	return head.Bytes(), nil
}

// collectAssigned gathers every name bound by assignment, augmented
// assignment, or a for target, without descending into nested defs.
func collectAssigned(body []frontend.Stmt, out map[string]bool) {
	var walkTarget func(t frontend.Expr)
	walkTarget = func(t frontend.Expr) {
		switch t := t.(type) {
		case *frontend.Name:
			out[t.Id] = true
		case *frontend.TupleLit:
			for _, el := range t.Elts {
				walkTarget(el)
			}
		}
	}
	var walk func(list []frontend.Stmt)
	walk = func(list []frontend.Stmt) {
		for _, s := range list {
			switch s := s.(type) {
			case *frontend.Assign:
				for _, t := range s.Targets {
					walkTarget(t)
				}
			case *frontend.AugAssign:
				walkTarget(s.Target)
			case *frontend.If:
				walk(s.Body)
				walk(s.Else)
			case *frontend.While:
				walk(s.Body)
				walk(s.Else)
			case *frontend.For:
				walkTarget(s.Target)
				walk(s.Body)
				walk(s.Else)
			}
		}
	}
	walk(body)
}

func sortedNames(set map[string]bool) []string {
	names := make([]string, 0, len(set))
	for n := range set {
		names = append(names, n)
	}
	for i := 1; i < len(names); i++ {
		for j := i; j > 0 && names[j] < names[j-1]; j-- {
			names[j], names[j-1] = names[j-1], names[j]
		}
	}
	return names
}

// --- statements ---

func (f *fnCtx) stmts(list []frontend.Stmt) error {
	for _, s := range list {
		if err := f.stmt(s); err != nil {
			return err
		}
	}
	return nil
}

func (f *fnCtx) stmt(s frontend.Stmt) error {
	switch s := s.(type) {
	case *frontend.ExprStmt:
		v, err := f.expr(s.X)
		if err != nil {
			return err
		}
		f.linef("_ = %s", v)
		return nil
	case *frontend.Assign:
		return f.assign(s)
	case *frontend.AugAssign:
		return f.augAssign(s)
	case *frontend.If:
		return f.ifStmt(s)
	case *frontend.While:
		return f.whileStmt(s)
	case *frontend.For:
		return f.forStmt(s)
	case *frontend.Return:
		if !f.inFunc {
			return f.e.errf(s.Span(), "'return' outside function")
		}
		if s.Value == nil {
			f.linef("return %s, nil", f.e.obj("None"))
			return nil
		}
		v, err := f.expr(s.Value)
		if err != nil {
			return err
		}
		f.linef("return %s, nil", v)
		return nil
	case *frontend.Pass:
		return nil
	case *frontend.Break:
		if len(f.loops) == 0 {
			return f.e.errf(s.Span(), "'break' outside loop")
		}
		if flag := f.loops[len(f.loops)-1].flag; flag != "" {
			f.linef("%s = true", flag)
		}
		f.line("break")
		return nil
	case *frontend.Continue:
		if len(f.loops) == 0 {
			return f.e.errf(s.Span(), "'continue' not properly in loop")
		}
		f.line("continue")
		return nil
	case *frontend.FuncDef:
		return f.e.errf(s.Span(), "nested def is not supported in M0")
	default:
		return f.e.errf(s.Span(), "statement not supported in M0")
	}
}

func (f *fnCtx) assign(s *frontend.Assign) error {
	v, err := f.expr(s.Value)
	if err != nil {
		return err
	}
	for _, t := range s.Targets {
		if err := f.assignTo(t, v); err != nil {
			return err
		}
	}
	return nil
}

func (f *fnCtx) assignTo(target frontend.Expr, v string) error {
	switch t := target.(type) {
	case *frontend.Name:
		f.linef("%s = %s", mangle(t.Id), v)
		return nil
	case *frontend.Subscript:
		x, err := f.expr(t.X)
		if err != nil {
			return err
		}
		idx, err := f.expr(t.Index)
		if err != nil {
			return err
		}
		f.linef("if err := %s(%s, %s, %s); err != nil {", f.e.obj("SetItem"), x, idx, v)
		f.indent++
		f.line(f.errRet())
		f.indent--
		f.line("}")
		return nil
	case *frontend.TupleLit:
		parts := f.newTmp()
		f.linef("%s, err := %s(%s, %d)", parts, f.e.obj("Unpack"), v, len(t.Elts))
		f.check()
		for i, el := range t.Elts {
			if err := f.assignTo(el, fmt.Sprintf("%s[%d]", parts, i)); err != nil {
				return err
			}
		}
		return nil
	default:
		return f.e.errf(target.Span(), "cannot assign to this expression")
	}
}

func (f *fnCtx) augAssign(s *frontend.AugAssign) error {
	op, ok := binFuncs[s.Op]
	if !ok {
		return f.e.errf(s.Span(), "augmented operator not supported in M0")
	}
	switch t := s.Target.(type) {
	case *frontend.Name:
		v, err := f.expr(s.Value)
		if err != nil {
			return err
		}
		tmp := f.newTmp()
		f.linef("%s, err := %s(%s, %s)", tmp, f.e.obj(op), mangle(t.Id), v)
		f.check()
		f.linef("%s = %s", mangle(t.Id), tmp)
		return nil
	case *frontend.Subscript:
		x, err := f.expr(t.X)
		if err != nil {
			return err
		}
		idx, err := f.expr(t.Index)
		if err != nil {
			return err
		}
		cur := f.newTmp()
		f.linef("%s, err := %s(%s, %s)", cur, f.e.obj("GetItem"), x, idx)
		f.check()
		v, err := f.expr(s.Value)
		if err != nil {
			return err
		}
		res := f.newTmp()
		f.linef("%s, err := %s(%s, %s)", res, f.e.obj(op), cur, v)
		f.check()
		f.linef("if err := %s(%s, %s, %s); err != nil {", f.e.obj("SetItem"), x, idx, res)
		f.indent++
		f.line(f.errRet())
		f.indent--
		f.line("}")
		return nil
	default:
		return f.e.errf(s.Span(), "augmented assignment target must be a name or subscript")
	}
}

func (f *fnCtx) ifStmt(s *frontend.If) error {
	cond, err := f.expr(s.Cond)
	if err != nil {
		return err
	}
	f.linef("if %s(%s) {", f.e.obj("Truth"), cond)
	f.indent++
	if err := f.stmts(s.Body); err != nil {
		return err
	}
	f.indent--
	if len(s.Else) == 0 {
		f.line("}")
		return nil
	}
	f.line("} else {")
	f.indent++
	if err := f.stmts(s.Else); err != nil {
		return err
	}
	f.indent--
	f.line("}")
	return nil
}

func (f *fnCtx) whileStmt(s *frontend.While) error {
	loop := &loopInfo{}
	if len(s.Else) > 0 {
		loop.flag = f.newTmp()
		f.linef("%s := false", loop.flag)
	}
	f.line("for {")
	f.indent++
	cond, err := f.expr(s.Cond)
	if err != nil {
		return err
	}
	f.linef("if !%s(%s) {", f.e.obj("Truth"), cond)
	f.indent++
	f.line("break")
	f.indent--
	f.line("}")
	f.loops = append(f.loops, loop)
	if err := f.stmts(s.Body); err != nil {
		return err
	}
	f.loops = f.loops[:len(f.loops)-1]
	f.indent--
	f.line("}")
	return f.loopElse(loop, s.Else)
}

func (f *fnCtx) forStmt(s *frontend.For) error {
	iter, err := f.expr(s.Iter)
	if err != nil {
		return err
	}
	it := f.newTmp()
	f.linef("%s, err := %s(%s)", it, f.e.obj("Iter"), iter)
	f.check()
	loop := &loopInfo{}
	if len(s.Else) > 0 {
		loop.flag = f.newTmp()
		f.linef("%s := false", loop.flag)
	}
	f.line("for {")
	f.indent++
	v := f.newTmp()
	ok := f.newTmp()
	f.linef("%s, %s, err := %s.Next()", v, ok, it)
	f.check()
	f.linef("if !%s {", ok)
	f.indent++
	f.line("break")
	f.indent--
	f.line("}")
	if err := f.assignTo(s.Target, v); err != nil {
		return err
	}
	f.loops = append(f.loops, loop)
	if err := f.stmts(s.Body); err != nil {
		return err
	}
	f.loops = f.loops[:len(f.loops)-1]
	f.indent--
	f.line("}")
	return f.loopElse(loop, s.Else)
}

// loopElse emits the else block guarded by the broke-out flag. Python runs a
// loop's else exactly when the loop finished without a break.
func (f *fnCtx) loopElse(loop *loopInfo, body []frontend.Stmt) error {
	if len(body) == 0 {
		return nil
	}
	f.linef("if !%s {", loop.flag)
	f.indent++
	if err := f.stmts(body); err != nil {
		return err
	}
	f.indent--
	f.line("}")
	return nil
}

// --- expressions ---

var binFuncs = map[frontend.BinKind]string{
	frontend.BinAdd:      "Add",
	frontend.BinSub:      "Sub",
	frontend.BinMul:      "Mul",
	frontend.BinDiv:      "TrueDiv",
	frontend.BinFloorDiv: "FloorDiv",
	frontend.BinMod:      "Mod",
	frontend.BinPow:      "Pow",
}

var cmpOps = map[frontend.CmpKind]string{
	frontend.CmpEq: "OpEq",
	frontend.CmpNe: "OpNe",
	frontend.CmpLt: "OpLt",
	frontend.CmpLe: "OpLe",
	frontend.CmpGt: "OpGt",
	frontend.CmpGe: "OpGe",
}

// expr lowers an expression, appending any needed temporaries, and returns a
// Go expression string holding the objects.Object value.
func (f *fnCtx) expr(e frontend.Expr) (string, error) {
	switch e := e.(type) {
	case *frontend.IntLit:
		n, err := strconv.ParseInt(e.Text, 10, 64)
		if err != nil {
			return "", f.e.errf(e.Span(), "integer literal exceeds the M0 int64 range")
		}
		return fmt.Sprintf("%s(%d)", f.e.obj("NewInt"), n), nil
	case *frontend.FloatLit:
		return fmt.Sprintf("%s(%s)", f.e.obj("NewFloat"), strconv.FormatFloat(e.Val, 'g', -1, 64)), nil
	case *frontend.StrLit:
		return fmt.Sprintf("%s(%s)", f.e.obj("NewStr"), strconv.Quote(e.Val)), nil
	case *frontend.BoolLit:
		if e.Val {
			return f.e.obj("True"), nil
		}
		return f.e.obj("False"), nil
	case *frontend.NoneLit:
		return f.e.obj("None"), nil
	case *frontend.Name:
		if f.locals[e.Id] {
			return mangle(e.Id), nil
		}
		if _, isDef := f.e.defs[e.Id]; isDef {
			return "", f.e.errf(e.Span(), "using function %q as a value is not supported in M0", e.Id)
		}
		if builtinNames[e.Id] {
			return "", f.e.errf(e.Span(), "using builtin %q as a value is not supported in M0", e.Id)
		}
		return "", f.e.errf(e.Span(), "name %q is not defined", e.Id)
	case *frontend.ListLit:
		elts, err := f.exprList(e.Elts)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s(%s)", f.e.obj("NewList"), f.objSlice(elts)), nil
	case *frontend.TupleLit:
		elts, err := f.exprList(e.Elts)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s(%s)", f.e.obj("NewTuple"), f.objSlice(elts)), nil
	case *frontend.DictLit:
		keys, err := f.exprList(e.Keys)
		if err != nil {
			return "", err
		}
		vals, err := f.exprList(e.Vals)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := %s(%s, %s)", tmp, f.e.obj("NewDict"), f.objSlice(keys), f.objSlice(vals))
		f.check()
		return tmp, nil
	case *frontend.BinOp:
		left, err := f.expr(e.Left)
		if err != nil {
			return "", err
		}
		right, err := f.expr(e.Right)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := %s(%s, %s)", tmp, f.e.obj(binFuncs[e.Op]), left, right)
		f.check()
		return tmp, nil
	case *frontend.UnaryOp:
		x, err := f.expr(e.X)
		if err != nil {
			return "", err
		}
		switch e.Op {
		case frontend.UnaryNot:
			return fmt.Sprintf("%s(%s)", f.e.obj("Not"), x), nil
		case frontend.UnaryNeg:
			tmp := f.newTmp()
			f.linef("%s, err := %s(%s)", tmp, f.e.obj("Neg"), x)
			f.check()
			return tmp, nil
		default:
			tmp := f.newTmp()
			f.linef("%s, err := %s(%s)", tmp, f.e.obj("Pos"), x)
			f.check()
			return tmp, nil
		}
	case *frontend.BoolOp:
		return f.boolOp(e)
	case *frontend.Compare:
		return f.compare(e)
	case *frontend.Call:
		return f.call(e)
	case *frontend.Subscript:
		x, err := f.expr(e.X)
		if err != nil {
			return "", err
		}
		idx, err := f.expr(e.Index)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := %s(%s, %s)", tmp, f.e.obj("GetItem"), x, idx)
		f.check()
		return tmp, nil
	case *frontend.Attribute:
		return "", f.e.errf(e.Span(), "attribute access outside a method call is not supported in M0")
	default:
		return "", f.e.errf(e.Span(), "expression not supported in M0")
	}
}

func (f *fnCtx) exprList(list []frontend.Expr) ([]string, error) {
	out := make([]string, len(list))
	for i, e := range list {
		v, err := f.expr(e)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

func (f *fnCtx) objSlice(elts []string) string {
	var b bytes.Buffer
	b.WriteString("[]" + f.e.obj("Object") + "{")
	for i, el := range elts {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(el)
	}
	b.WriteString("}")
	return b.String()
}

// boolOp lowers and/or with Python's short-circuit and value-passing
// semantics: the result is the last operand evaluated, not a bool.
func (f *fnCtx) boolOp(e *frontend.BoolOp) (string, error) {
	first, err := f.expr(e.Values[0])
	if err != nil {
		return "", err
	}
	res := f.newTmp()
	f.linef("%s := %s", res, first)
	if err := f.boolOpRest(e, 1, res); err != nil {
		return "", err
	}
	return res, nil
}

func (f *fnCtx) boolOpRest(e *frontend.BoolOp, i int, res string) error {
	if i >= len(e.Values) {
		return nil
	}
	if e.Kind == frontend.BoolAnd {
		f.linef("if %s(%s) {", f.e.obj("Truth"), res)
	} else {
		f.linef("if !%s(%s) {", f.e.obj("Truth"), res)
	}
	f.indent++
	v, err := f.expr(e.Values[i])
	if err != nil {
		return err
	}
	f.linef("%s = %s", res, v)
	if err := f.boolOpRest(e, i+1, res); err != nil {
		return err
	}
	f.indent--
	f.line("}")
	return nil
}

// compare lowers a possibly chained comparison. Each middle operand is
// evaluated once, and the chain short-circuits on the first false link, both
// per the language reference.
func (f *fnCtx) compare(e *frontend.Compare) (string, error) {
	left, err := f.expr(e.Left)
	if err != nil {
		return "", err
	}
	right, err := f.expr(e.Rights[0])
	if err != nil {
		return "", err
	}
	res := f.newTmp()
	if err := f.compareOne(e.Ops[0], left, right, res); err != nil {
		return "", err
	}
	if err := f.compareRest(e, 1, right, res); err != nil {
		return "", err
	}
	return res, nil
}

func (f *fnCtx) compareRest(e *frontend.Compare, i int, prev, res string) error {
	if i >= len(e.Ops) {
		return nil
	}
	f.linef("if %s(%s) {", f.e.obj("Truth"), res)
	f.indent++
	right, err := f.expr(e.Rights[i])
	if err != nil {
		return err
	}
	link := f.newTmp()
	if err := f.compareOne(e.Ops[i], prev, right, link); err != nil {
		return err
	}
	f.linef("%s = %s", res, link)
	if err := f.compareRest(e, i+1, right, res); err != nil {
		return err
	}
	f.indent--
	f.line("}")
	return nil
}

// compareOne emits a single comparison link, declaring dst as a fresh temp.
func (f *fnCtx) compareOne(op frontend.CmpKind, left, right, dst string) error {
	switch op {
	case frontend.CmpIn:
		f.linef("%s, err := %s(%s, %s)", dst, f.e.obj("Contains"), right, left)
		f.check()
	case frontend.CmpNotIn:
		tmp := f.newTmp()
		f.linef("%s, err := %s(%s, %s)", tmp, f.e.obj("Contains"), right, left)
		f.check()
		f.linef("%s := %s(%s)", dst, f.e.obj("Not"), tmp)
	case frontend.CmpIs:
		f.linef("%s := %s(%s, %s)", dst, f.e.obj("Is"), left, right)
	case frontend.CmpIsNot:
		f.linef("%s := %s(%s(%s, %s))", dst, f.e.obj("Not"), f.e.obj("Is"), left, right)
	default:
		f.linef("%s, err := %s(%s, %s, %s)", dst, f.e.obj("Compare"), f.e.obj(cmpOps[op]), left, right)
		f.check()
	}
	return nil
}

// call lowers a call expression. M0 resolves callees statically: a name bound
// by a module-level def becomes a direct Go call, an unshadowed builtin
// becomes its runtime helper, and a method call goes through CallMethod.
func (f *fnCtx) call(e *frontend.Call) (string, error) {
	if attr, ok := e.Fn.(*frontend.Attribute); ok {
		recv, err := f.expr(attr.X)
		if err != nil {
			return "", err
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := %s(%s, %q, %s)", tmp, f.e.obj("CallMethod"), recv, attr.Name, f.objSlice(args))
		f.check()
		return tmp, nil
	}
	name, ok := e.Fn.(*frontend.Name)
	if !ok {
		return "", f.e.errf(e.Span(), "only named functions, builtins, and methods are callable in M0")
	}
	if f.locals[name.Id] {
		return "", f.e.errf(e.Span(), "calling a variable is not supported in M0")
	}
	if d, isDef := f.e.defs[name.Id]; isDef {
		if len(e.Args) != len(d.Params) {
			return "", f.e.errf(e.Span(), "%s() takes %d positional arguments but %d were given",
				name.Id, len(d.Params), len(e.Args))
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := %s(%s)", tmp, mangle(name.Id), join(args))
		f.check()
		return tmp, nil
	}
	if builtinNames[name.Id] {
		return f.builtinCall(name.Id, e)
	}
	return "", f.e.errf(e.Span(), "name %q is not defined", name.Id)
}

func (f *fnCtx) builtinCall(name string, e *frontend.Call) (string, error) {
	argc := len(e.Args)
	need1 := func() error {
		if argc != 1 {
			return f.e.errf(e.Span(), "%s() takes exactly one argument (%d given)", name, argc)
		}
		return nil
	}
	switch name {
	case "print":
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		f.linef("if err := runtime.Print(%s); err != nil {", join(args))
		f.indent++
		f.line(f.errRet())
		f.indent--
		f.line("}")
		return f.e.obj("None"), nil
	case "len":
		if err := need1(); err != nil {
			return "", err
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := runtime.Len(%s)", tmp, args[0])
		f.check()
		return tmp, nil
	case "range":
		if argc < 1 || argc > 3 {
			return "", f.e.errf(e.Span(), "range expected 1 to 3 arguments, got %d", argc)
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := runtime.Range(%s)", tmp, join(args))
		f.check()
		return tmp, nil
	case "str":
		if argc == 0 {
			return fmt.Sprintf("%s(\"\")", f.e.obj("NewStr")), nil
		}
		if err := need1(); err != nil {
			return "", err
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("runtime.StrOf(%s)", args[0]), nil
	case "repr":
		if err := need1(); err != nil {
			return "", err
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("runtime.ReprOf(%s)", args[0]), nil
	case "int":
		if argc == 0 {
			return fmt.Sprintf("%s(0)", f.e.obj("NewInt")), nil
		}
		if err := need1(); err != nil {
			return "", err
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := runtime.IntOf(%s)", tmp, args[0])
		f.check()
		return tmp, nil
	case "float":
		if argc == 0 {
			return fmt.Sprintf("%s(0)", f.e.obj("NewFloat")), nil
		}
		if err := need1(); err != nil {
			return "", err
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := runtime.FloatOf(%s)", tmp, args[0])
		f.check()
		return tmp, nil
	case "bool":
		if argc == 0 {
			return f.e.obj("False"), nil
		}
		if err := need1(); err != nil {
			return "", err
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("runtime.BoolOf(%s)", args[0]), nil
	case "abs":
		if err := need1(); err != nil {
			return "", err
		}
		args, err := f.exprList(e.Args)
		if err != nil {
			return "", err
		}
		tmp := f.newTmp()
		f.linef("%s, err := runtime.Abs(%s)", tmp, args[0])
		f.check()
		return tmp, nil
	}
	return "", f.e.errf(e.Span(), "builtin %q is not supported in M0", name)
}

func join(parts []string) string {
	var b bytes.Buffer
	for i, p := range parts {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(p)
	}
	return b.String()
}
